# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Cmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Cmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Cmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Cmd
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Cmd
    def TType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Cmd
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def CmdStart(builder):
    builder.StartObject(3)

def Start(builder):
    CmdStart(builder)

def CmdAddHandle(builder, handle):
    builder.PrependUint32Slot(0, handle, 0)

def AddHandle(builder, handle):
    CmdAddHandle(builder, handle)

def CmdAddTType(builder, tType):
    builder.PrependUint8Slot(1, tType, 0)

def AddTType(builder, tType):
    CmdAddTType(builder, tType)

def CmdAddT(builder, t):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(t), 0)

def AddT(builder, t):
    CmdAddT(builder, t)

def CmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdEnd(builder)

import FB.CmdAddRoute
import FB.CmdGetNeuron
import FB.CmdGetRegmem
import FB.CmdGetSynapse
import FB.CmdResetAll
import FB.CmdResetOdinCore
import FB.CmdResetRouter
import FB.CmdSendPacket
import FB.CmdSetNeuron
import FB.CmdSetRegmem
import FB.CmdSetServerOutput
import FB.CmdSetSynapse
import FB.CmdWaitIdle
import FB.CmdWaitOdinCore
import FB.Cmd_t
try:
    from typing import Union
except:
    pass

class CmdT(object):

    # CmdT
    def __init__(
        self,
        handle = 0,
        tType = 0,
        t = None,
    ):
        self.handle = handle  # type: int
        self.tType = tType  # type: int
        self.t = t  # type: Union[None, 'FB.CmdResetAll.CmdResetAllT', 'FB.CmdResetOdinCore.CmdResetOdinCoreT', 'FB.CmdWaitIdle.CmdWaitIdleT', 'FB.CmdWaitOdinCore.CmdWaitOdinCoreT', 'FB.CmdSendPacket.CmdSendPacketT', 'FB.CmdGetRegmem.CmdGetRegmemT', 'FB.CmdSetRegmem.CmdSetRegmemT', 'FB.CmdGetNeuron.CmdGetNeuronT', 'FB.CmdSetNeuron.CmdSetNeuronT', 'FB.CmdGetSynapse.CmdGetSynapseT', 'FB.CmdSetSynapse.CmdSetSynapseT', 'FB.CmdResetRouter.CmdResetRouterT', 'FB.CmdAddRoute.CmdAddRouteT', 'FB.CmdSetServerOutput.CmdSetServerOutputT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmd = Cmd()
        cmd.Init(buf, pos)
        return cls.InitFromObj(cmd)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmd):
        x = CmdT()
        x._UnPack(cmd)
        return x

    # CmdT
    def _UnPack(self, cmd):
        if cmd is None:
            return
        self.handle = cmd.Handle()
        self.tType = cmd.TType()
        self.t = FB.Cmd_t.CmdTCreator(self.tType, cmd.T())

    # CmdT
    def Pack(self, builder):
        if self.t is not None:
            t = self.t.Pack(builder)
        CmdStart(builder)
        CmdAddHandle(builder, self.handle)
        CmdAddTType(builder, self.tType)
        if self.t is not None:
            CmdAddT(builder, t)
        cmd = CmdEnd(builder)
        return cmd
