# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class Cmd_t(object):
    NONE = 0
    CmdResetAll = 1
    CmdResetOdinCore = 2
    CmdWaitIdle = 3
    CmdWaitOdinCore = 4
    CmdSendPacket = 5
    CmdGetRegmem = 6
    CmdSetRegmem = 7
    CmdGetNeuron = 8
    CmdSetNeuron = 9
    CmdGetSynapse = 10
    CmdSetSynapse = 11
    CmdResetRouter = 12
    CmdAddRoute = 13
    CmdSetServerOutput = 14

def CmdTCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Cmd_t.CmdResetAll:
        import FB.CmdResetAll
        return FB.CmdResetAll.CmdResetAllT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdResetOdinCore:
        import FB.CmdResetOdinCore
        return FB.CmdResetOdinCore.CmdResetOdinCoreT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdWaitIdle:
        import FB.CmdWaitIdle
        return FB.CmdWaitIdle.CmdWaitIdleT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdWaitOdinCore:
        import FB.CmdWaitOdinCore
        return FB.CmdWaitOdinCore.CmdWaitOdinCoreT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdSendPacket:
        import FB.CmdSendPacket
        return FB.CmdSendPacket.CmdSendPacketT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdGetRegmem:
        import FB.CmdGetRegmem
        return FB.CmdGetRegmem.CmdGetRegmemT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdSetRegmem:
        import FB.CmdSetRegmem
        return FB.CmdSetRegmem.CmdSetRegmemT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdGetNeuron:
        import FB.CmdGetNeuron
        return FB.CmdGetNeuron.CmdGetNeuronT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdSetNeuron:
        import FB.CmdSetNeuron
        return FB.CmdSetNeuron.CmdSetNeuronT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdGetSynapse:
        import FB.CmdGetSynapse
        return FB.CmdGetSynapse.CmdGetSynapseT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdSetSynapse:
        import FB.CmdSetSynapse
        return FB.CmdSetSynapse.CmdSetSynapseT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdResetRouter:
        import FB.CmdResetRouter
        return FB.CmdResetRouter.CmdResetRouterT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdAddRoute:
        import FB.CmdAddRoute
        return FB.CmdAddRoute.CmdAddRouteT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Cmd_t.CmdSetServerOutput:
        import FB.CmdSetServerOutput
        return FB.CmdSetServerOutput.CmdSetServerOutputT.InitFromBuf(table.Bytes, table.Pos)
    return None
