# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdAddRoute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdAddRoute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdAddRoute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdAddRoute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdAddRoute
    def FromCore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdAddRoute
    def FromNeur(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdAddRoute
    def ToCore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdAddRoute
    def EventAddr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def CmdAddRouteStart(builder):
    builder.StartObject(4)

def Start(builder):
    CmdAddRouteStart(builder)

def CmdAddRouteAddFromCore(builder, fromCore):
    builder.PrependUint8Slot(0, fromCore, 0)

def AddFromCore(builder, fromCore):
    CmdAddRouteAddFromCore(builder, fromCore)

def CmdAddRouteAddFromNeur(builder, fromNeur):
    builder.PrependUint8Slot(1, fromNeur, 0)

def AddFromNeur(builder, fromNeur):
    CmdAddRouteAddFromNeur(builder, fromNeur)

def CmdAddRouteAddToCore(builder, toCore):
    builder.PrependUint8Slot(2, toCore, 0)

def AddToCore(builder, toCore):
    CmdAddRouteAddToCore(builder, toCore)

def CmdAddRouteAddEventAddr(builder, eventAddr):
    builder.PrependUint32Slot(3, eventAddr, 0)

def AddEventAddr(builder, eventAddr):
    CmdAddRouteAddEventAddr(builder, eventAddr)

def CmdAddRouteEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdAddRouteEnd(builder)


class CmdAddRouteT(object):

    # CmdAddRouteT
    def __init__(
        self,
        fromCore = 0,
        fromNeur = 0,
        toCore = 0,
        eventAddr = 0,
    ):
        self.fromCore = fromCore  # type: int
        self.fromNeur = fromNeur  # type: int
        self.toCore = toCore  # type: int
        self.eventAddr = eventAddr  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdAddRoute = CmdAddRoute()
        cmdAddRoute.Init(buf, pos)
        return cls.InitFromObj(cmdAddRoute)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdAddRoute):
        x = CmdAddRouteT()
        x._UnPack(cmdAddRoute)
        return x

    # CmdAddRouteT
    def _UnPack(self, cmdAddRoute):
        if cmdAddRoute is None:
            return
        self.fromCore = cmdAddRoute.FromCore()
        self.fromNeur = cmdAddRoute.FromNeur()
        self.toCore = cmdAddRoute.ToCore()
        self.eventAddr = cmdAddRoute.EventAddr()

    # CmdAddRouteT
    def Pack(self, builder):
        CmdAddRouteStart(builder)
        CmdAddRouteAddFromCore(builder, self.fromCore)
        CmdAddRouteAddFromNeur(builder, self.fromNeur)
        CmdAddRouteAddToCore(builder, self.toCore)
        CmdAddRouteAddEventAddr(builder, self.eventAddr)
        cmdAddRoute = CmdAddRouteEnd(builder)
        return cmdAddRoute
