# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdGetRegmem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdGetRegmem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdGetRegmem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdGetRegmem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdGetRegmem
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def CmdGetRegmemStart(builder):
    builder.StartObject(1)

def Start(builder):
    CmdGetRegmemStart(builder)

def CmdGetRegmemAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdGetRegmemAddCoreId(builder, coreId)

def CmdGetRegmemEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdGetRegmemEnd(builder)


class CmdGetRegmemT(object):

    # CmdGetRegmemT
    def __init__(
        self,
        coreId = 0,
    ):
        self.coreId = coreId  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdGetRegmem = CmdGetRegmem()
        cmdGetRegmem.Init(buf, pos)
        return cls.InitFromObj(cmdGetRegmem)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdGetRegmem):
        x = CmdGetRegmemT()
        x._UnPack(cmdGetRegmem)
        return x

    # CmdGetRegmemT
    def _UnPack(self, cmdGetRegmem):
        if cmdGetRegmem is None:
            return
        self.coreId = cmdGetRegmem.CoreId()

    # CmdGetRegmemT
    def Pack(self, builder):
        CmdGetRegmemStart(builder)
        CmdGetRegmemAddCoreId(builder, self.coreId)
        cmdGetRegmem = CmdGetRegmemEnd(builder)
        return cmdGetRegmem
