# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdGetNeuron(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdGetNeuron()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdGetNeuron(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdGetNeuron
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdGetNeuron
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdGetNeuron
    def NeurId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def CmdGetNeuronStart(builder):
    builder.StartObject(2)

def Start(builder):
    CmdGetNeuronStart(builder)

def CmdGetNeuronAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdGetNeuronAddCoreId(builder, coreId)

def CmdGetNeuronAddNeurId(builder, neurId):
    builder.PrependUint32Slot(1, neurId, 0)

def AddNeurId(builder, neurId):
    CmdGetNeuronAddNeurId(builder, neurId)

def CmdGetNeuronEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdGetNeuronEnd(builder)


class CmdGetNeuronT(object):

    # CmdGetNeuronT
    def __init__(
        self,
        coreId = 0,
        neurId = 0,
    ):
        self.coreId = coreId  # type: int
        self.neurId = neurId  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdGetNeuron = CmdGetNeuron()
        cmdGetNeuron.Init(buf, pos)
        return cls.InitFromObj(cmdGetNeuron)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdGetNeuron):
        x = CmdGetNeuronT()
        x._UnPack(cmdGetNeuron)
        return x

    # CmdGetNeuronT
    def _UnPack(self, cmdGetNeuron):
        if cmdGetNeuron is None:
            return
        self.coreId = cmdGetNeuron.CoreId()
        self.neurId = cmdGetNeuron.NeurId()

    # CmdGetNeuronT
    def Pack(self, builder):
        CmdGetNeuronStart(builder)
        CmdGetNeuronAddCoreId(builder, self.coreId)
        CmdGetNeuronAddNeurId(builder, self.neurId)
        cmdGetNeuron = CmdGetNeuronEnd(builder)
        return cmdGetNeuron
