# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdGetSynapse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdGetSynapse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdGetSynapse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdGetSynapse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdGetSynapse
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdGetSynapse
    def PreNeurId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CmdGetSynapse
    def PostNeurId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def CmdGetSynapseStart(builder):
    builder.StartObject(3)

def Start(builder):
    CmdGetSynapseStart(builder)

def CmdGetSynapseAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdGetSynapseAddCoreId(builder, coreId)

def CmdGetSynapseAddPreNeurId(builder, preNeurId):
    builder.PrependUint32Slot(1, preNeurId, 0)

def AddPreNeurId(builder, preNeurId):
    CmdGetSynapseAddPreNeurId(builder, preNeurId)

def CmdGetSynapseAddPostNeurId(builder, postNeurId):
    builder.PrependUint32Slot(2, postNeurId, 0)

def AddPostNeurId(builder, postNeurId):
    CmdGetSynapseAddPostNeurId(builder, postNeurId)

def CmdGetSynapseEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdGetSynapseEnd(builder)


class CmdGetSynapseT(object):

    # CmdGetSynapseT
    def __init__(
        self,
        coreId = 0,
        preNeurId = 0,
        postNeurId = 0,
    ):
        self.coreId = coreId  # type: int
        self.preNeurId = preNeurId  # type: int
        self.postNeurId = postNeurId  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdGetSynapse = CmdGetSynapse()
        cmdGetSynapse.Init(buf, pos)
        return cls.InitFromObj(cmdGetSynapse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdGetSynapse):
        x = CmdGetSynapseT()
        x._UnPack(cmdGetSynapse)
        return x

    # CmdGetSynapseT
    def _UnPack(self, cmdGetSynapse):
        if cmdGetSynapse is None:
            return
        self.coreId = cmdGetSynapse.CoreId()
        self.preNeurId = cmdGetSynapse.PreNeurId()
        self.postNeurId = cmdGetSynapse.PostNeurId()

    # CmdGetSynapseT
    def Pack(self, builder):
        CmdGetSynapseStart(builder)
        CmdGetSynapseAddCoreId(builder, self.coreId)
        CmdGetSynapseAddPreNeurId(builder, self.preNeurId)
        CmdGetSynapseAddPostNeurId(builder, self.postNeurId)
        cmdGetSynapse = CmdGetSynapseEnd(builder)
        return cmdGetSynapse
