# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdOutputGetRegmem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdOutputGetRegmem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdOutputGetRegmem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdOutputGetRegmem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdOutputGetRegmem
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdOutputGetRegmem
    def Regmem(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from FB.OdinRegmem import OdinRegmem
            obj = OdinRegmem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CmdOutputGetRegmemStart(builder):
    builder.StartObject(2)

def Start(builder):
    CmdOutputGetRegmemStart(builder)

def CmdOutputGetRegmemAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdOutputGetRegmemAddCoreId(builder, coreId)

def CmdOutputGetRegmemAddRegmem(builder, regmem):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(regmem), 0)

def AddRegmem(builder, regmem):
    CmdOutputGetRegmemAddRegmem(builder, regmem)

def CmdOutputGetRegmemEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdOutputGetRegmemEnd(builder)

import FB.OdinRegmem
try:
    from typing import Optional
except:
    pass

class CmdOutputGetRegmemT(object):

    # CmdOutputGetRegmemT
    def __init__(
        self,
        coreId = 0,
        regmem = None,
    ):
        self.coreId = coreId  # type: int
        self.regmem = regmem  # type: Optional[FB.OdinRegmem.OdinRegmemT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdOutputGetRegmem = CmdOutputGetRegmem()
        cmdOutputGetRegmem.Init(buf, pos)
        return cls.InitFromObj(cmdOutputGetRegmem)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdOutputGetRegmem):
        x = CmdOutputGetRegmemT()
        x._UnPack(cmdOutputGetRegmem)
        return x

    # CmdOutputGetRegmemT
    def _UnPack(self, cmdOutputGetRegmem):
        if cmdOutputGetRegmem is None:
            return
        self.coreId = cmdOutputGetRegmem.CoreId()
        if cmdOutputGetRegmem.Regmem() is not None:
            self.regmem = FB.OdinRegmem.OdinRegmemT.InitFromObj(cmdOutputGetRegmem.Regmem())

    # CmdOutputGetRegmemT
    def Pack(self, builder):
        CmdOutputGetRegmemStart(builder)
        CmdOutputGetRegmemAddCoreId(builder, self.coreId)
        if self.regmem is not None:
            regmem = self.regmem.Pack(builder)
            CmdOutputGetRegmemAddRegmem(builder, regmem)
        cmdOutputGetRegmem = CmdOutputGetRegmemEnd(builder)
        return cmdOutputGetRegmem
