# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdOutputGetSynapse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdOutputGetSynapse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdOutputGetSynapse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdOutputGetSynapse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdOutputGetSynapse
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdOutputGetSynapse
    def PreNeurId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CmdOutputGetSynapse
    def PostNeurId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CmdOutputGetSynapse
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def CmdOutputGetSynapseStart(builder):
    builder.StartObject(4)

def Start(builder):
    CmdOutputGetSynapseStart(builder)

def CmdOutputGetSynapseAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdOutputGetSynapseAddCoreId(builder, coreId)

def CmdOutputGetSynapseAddPreNeurId(builder, preNeurId):
    builder.PrependUint32Slot(1, preNeurId, 0)

def AddPreNeurId(builder, preNeurId):
    CmdOutputGetSynapseAddPreNeurId(builder, preNeurId)

def CmdOutputGetSynapseAddPostNeurId(builder, postNeurId):
    builder.PrependUint32Slot(2, postNeurId, 0)

def AddPostNeurId(builder, postNeurId):
    CmdOutputGetSynapseAddPostNeurId(builder, postNeurId)

def CmdOutputGetSynapseAddWeight(builder, weight):
    builder.PrependUint8Slot(3, weight, 0)

def AddWeight(builder, weight):
    CmdOutputGetSynapseAddWeight(builder, weight)

def CmdOutputGetSynapseEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdOutputGetSynapseEnd(builder)


class CmdOutputGetSynapseT(object):

    # CmdOutputGetSynapseT
    def __init__(
        self,
        coreId = 0,
        preNeurId = 0,
        postNeurId = 0,
        weight = 0,
    ):
        self.coreId = coreId  # type: int
        self.preNeurId = preNeurId  # type: int
        self.postNeurId = postNeurId  # type: int
        self.weight = weight  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdOutputGetSynapse = CmdOutputGetSynapse()
        cmdOutputGetSynapse.Init(buf, pos)
        return cls.InitFromObj(cmdOutputGetSynapse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdOutputGetSynapse):
        x = CmdOutputGetSynapseT()
        x._UnPack(cmdOutputGetSynapse)
        return x

    # CmdOutputGetSynapseT
    def _UnPack(self, cmdOutputGetSynapse):
        if cmdOutputGetSynapse is None:
            return
        self.coreId = cmdOutputGetSynapse.CoreId()
        self.preNeurId = cmdOutputGetSynapse.PreNeurId()
        self.postNeurId = cmdOutputGetSynapse.PostNeurId()
        self.weight = cmdOutputGetSynapse.Weight()

    # CmdOutputGetSynapseT
    def Pack(self, builder):
        CmdOutputGetSynapseStart(builder)
        CmdOutputGetSynapseAddCoreId(builder, self.coreId)
        CmdOutputGetSynapseAddPreNeurId(builder, self.preNeurId)
        CmdOutputGetSynapseAddPostNeurId(builder, self.postNeurId)
        CmdOutputGetSynapseAddWeight(builder, self.weight)
        cmdOutputGetSynapse = CmdOutputGetSynapseEnd(builder)
        return cmdOutputGetSynapse
