# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdOutputNone(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdOutputNone()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdOutputNone(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdOutputNone
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def CmdOutputNoneStart(builder):
    builder.StartObject(0)

def Start(builder):
    CmdOutputNoneStart(builder)

def CmdOutputNoneEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdOutputNoneEnd(builder)


class CmdOutputNoneT(object):

    # CmdOutputNoneT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdOutputNone = CmdOutputNone()
        cmdOutputNone.Init(buf, pos)
        return cls.InitFromObj(cmdOutputNone)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdOutputNone):
        x = CmdOutputNoneT()
        x._UnPack(cmdOutputNone)
        return x

    # CmdOutputNoneT
    def _UnPack(self, cmdOutputNone):
        if cmdOutputNone is None:
            return

    # CmdOutputNoneT
    def Pack(self, builder):
        CmdOutputNoneStart(builder)
        cmdOutputNone = CmdOutputNoneEnd(builder)
        return cmdOutputNone
