# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class CmdOutput_t(object):
    NONE = 0
    CmdOutputNone = 1
    CmdOutputGetRegmem = 2
    CmdOutputGetNeuron = 3
    CmdOutputGetSynapse = 4

def CmdOutputTCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == CmdOutput_t.CmdOutputNone:
        import FB.CmdOutputNone
        return FB.CmdOutputNone.CmdOutputNoneT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == CmdOutput_t.CmdOutputGetRegmem:
        import FB.CmdOutputGetRegmem
        return FB.CmdOutputGetRegmem.CmdOutputGetRegmemT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == CmdOutput_t.CmdOutputGetNeuron:
        import FB.CmdOutputGetNeuron
        return FB.CmdOutputGetNeuron.CmdOutputGetNeuronT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == CmdOutput_t.CmdOutputGetSynapse:
        import FB.CmdOutputGetSynapse
        return FB.CmdOutputGetSynapse.CmdOutputGetSynapseT.InitFromBuf(table.Bytes, table.Pos)
    return None
