# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdOutput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdOutput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdOutput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdOutput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdOutput
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CmdOutput
    def TType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdOutput
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def CmdOutputStart(builder):
    builder.StartObject(3)

def Start(builder):
    CmdOutputStart(builder)

def CmdOutputAddHandle(builder, handle):
    builder.PrependUint32Slot(0, handle, 0)

def AddHandle(builder, handle):
    CmdOutputAddHandle(builder, handle)

def CmdOutputAddTType(builder, tType):
    builder.PrependUint8Slot(1, tType, 0)

def AddTType(builder, tType):
    CmdOutputAddTType(builder, tType)

def CmdOutputAddT(builder, t):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(t), 0)

def AddT(builder, t):
    CmdOutputAddT(builder, t)

def CmdOutputEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdOutputEnd(builder)

import FB.CmdOutputGetNeuron
import FB.CmdOutputGetRegmem
import FB.CmdOutputGetSynapse
import FB.CmdOutputNone
import FB.CmdOutput_t
try:
    from typing import Union
except:
    pass

class CmdOutputT(object):

    # CmdOutputT
    def __init__(
        self,
        handle = 0,
        tType = 0,
        t = None,
    ):
        self.handle = handle  # type: int
        self.tType = tType  # type: int
        self.t = t  # type: Union[None, 'FB.CmdOutputNone.CmdOutputNoneT', 'FB.CmdOutputGetRegmem.CmdOutputGetRegmemT', 'FB.CmdOutputGetNeuron.CmdOutputGetNeuronT', 'FB.CmdOutputGetSynapse.CmdOutputGetSynapseT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdOutput = CmdOutput()
        cmdOutput.Init(buf, pos)
        return cls.InitFromObj(cmdOutput)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdOutput):
        x = CmdOutputT()
        x._UnPack(cmdOutput)
        return x

    # CmdOutputT
    def _UnPack(self, cmdOutput):
        if cmdOutput is None:
            return
        self.handle = cmdOutput.Handle()
        self.tType = cmdOutput.TType()
        self.t = FB.CmdOutput_t.CmdOutputTCreator(self.tType, cmdOutput.T())

    # CmdOutputT
    def Pack(self, builder):
        if self.t is not None:
            t = self.t.Pack(builder)
        CmdOutputStart(builder)
        CmdOutputAddHandle(builder, self.handle)
        CmdOutputAddTType(builder, self.tType)
        if self.t is not None:
            CmdOutputAddT(builder, t)
        cmdOutput = CmdOutputEnd(builder)
        return cmdOutput
