# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdOutputGetNeuron(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdOutputGetNeuron()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdOutputGetNeuron(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdOutputGetNeuron
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdOutputGetNeuron
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdOutputGetNeuron
    def NeurId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CmdOutputGetNeuron
    def NeuronWords(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from FB.NeuronWords128 import NeuronWords128
            obj = NeuronWords128()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CmdOutputGetNeuronStart(builder):
    builder.StartObject(3)

def Start(builder):
    CmdOutputGetNeuronStart(builder)

def CmdOutputGetNeuronAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdOutputGetNeuronAddCoreId(builder, coreId)

def CmdOutputGetNeuronAddNeurId(builder, neurId):
    builder.PrependUint32Slot(1, neurId, 0)

def AddNeurId(builder, neurId):
    CmdOutputGetNeuronAddNeurId(builder, neurId)

def CmdOutputGetNeuronAddNeuronWords(builder, neuronWords):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(neuronWords), 0)

def AddNeuronWords(builder, neuronWords):
    CmdOutputGetNeuronAddNeuronWords(builder, neuronWords)

def CmdOutputGetNeuronEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdOutputGetNeuronEnd(builder)

import FB.NeuronWords128
try:
    from typing import Optional
except:
    pass

class CmdOutputGetNeuronT(object):

    # CmdOutputGetNeuronT
    def __init__(
        self,
        coreId = 0,
        neurId = 0,
        neuronWords = None,
    ):
        self.coreId = coreId  # type: int
        self.neurId = neurId  # type: int
        self.neuronWords = neuronWords  # type: Optional[FB.NeuronWords128.NeuronWords128T]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdOutputGetNeuron = CmdOutputGetNeuron()
        cmdOutputGetNeuron.Init(buf, pos)
        return cls.InitFromObj(cmdOutputGetNeuron)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdOutputGetNeuron):
        x = CmdOutputGetNeuronT()
        x._UnPack(cmdOutputGetNeuron)
        return x

    # CmdOutputGetNeuronT
    def _UnPack(self, cmdOutputGetNeuron):
        if cmdOutputGetNeuron is None:
            return
        self.coreId = cmdOutputGetNeuron.CoreId()
        self.neurId = cmdOutputGetNeuron.NeurId()
        if cmdOutputGetNeuron.NeuronWords() is not None:
            self.neuronWords = FB.NeuronWords128.NeuronWords128T.InitFromObj(cmdOutputGetNeuron.NeuronWords())

    # CmdOutputGetNeuronT
    def Pack(self, builder):
        CmdOutputGetNeuronStart(builder)
        CmdOutputGetNeuronAddCoreId(builder, self.coreId)
        CmdOutputGetNeuronAddNeurId(builder, self.neurId)
        if self.neuronWords is not None:
            neuronWords = self.neuronWords.Pack(builder)
            CmdOutputGetNeuronAddNeuronWords(builder, neuronWords)
        cmdOutputGetNeuron = CmdOutputGetNeuronEnd(builder)
        return cmdOutputGetNeuron
