# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdResetRouter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdResetRouter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdResetRouter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdResetRouter
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def CmdResetRouterStart(builder):
    builder.StartObject(0)

def Start(builder):
    CmdResetRouterStart(builder)

def CmdResetRouterEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdResetRouterEnd(builder)


class CmdResetRouterT(object):

    # CmdResetRouterT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdResetRouter = CmdResetRouter()
        cmdResetRouter.Init(buf, pos)
        return cls.InitFromObj(cmdResetRouter)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdResetRouter):
        x = CmdResetRouterT()
        x._UnPack(cmdResetRouter)
        return x

    # CmdResetRouterT
    def _UnPack(self, cmdResetRouter):
        if cmdResetRouter is None:
            return

    # CmdResetRouterT
    def Pack(self, builder):
        CmdResetRouterStart(builder)
        cmdResetRouter = CmdResetRouterEnd(builder)
        return cmdResetRouter
