# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdResetOdinCore(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdResetOdinCore()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdResetOdinCore(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdResetOdinCore
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdResetOdinCore
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def CmdResetOdinCoreStart(builder):
    builder.StartObject(1)

def Start(builder):
    CmdResetOdinCoreStart(builder)

def CmdResetOdinCoreAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdResetOdinCoreAddCoreId(builder, coreId)

def CmdResetOdinCoreEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdResetOdinCoreEnd(builder)


class CmdResetOdinCoreT(object):

    # CmdResetOdinCoreT
    def __init__(
        self,
        coreId = 0,
    ):
        self.coreId = coreId  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdResetOdinCore = CmdResetOdinCore()
        cmdResetOdinCore.Init(buf, pos)
        return cls.InitFromObj(cmdResetOdinCore)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdResetOdinCore):
        x = CmdResetOdinCoreT()
        x._UnPack(cmdResetOdinCore)
        return x

    # CmdResetOdinCoreT
    def _UnPack(self, cmdResetOdinCore):
        if cmdResetOdinCore is None:
            return
        self.coreId = cmdResetOdinCore.CoreId()

    # CmdResetOdinCoreT
    def Pack(self, builder):
        CmdResetOdinCoreStart(builder)
        CmdResetOdinCoreAddCoreId(builder, self.coreId)
        cmdResetOdinCore = CmdResetOdinCoreEnd(builder)
        return cmdResetOdinCore
