# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdResetAll(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdResetAll()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdResetAll(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdResetAll
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def CmdResetAllStart(builder):
    builder.StartObject(0)

def Start(builder):
    CmdResetAllStart(builder)

def CmdResetAllEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdResetAllEnd(builder)


class CmdResetAllT(object):

    # CmdResetAllT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdResetAll = CmdResetAll()
        cmdResetAll.Init(buf, pos)
        return cls.InitFromObj(cmdResetAll)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdResetAll):
        x = CmdResetAllT()
        x._UnPack(cmdResetAll)
        return x

    # CmdResetAllT
    def _UnPack(self, cmdResetAll):
        if cmdResetAll is None:
            return

    # CmdResetAllT
    def Pack(self, builder):
        CmdResetAllStart(builder)
        cmdResetAll = CmdResetAllEnd(builder)
        return cmdResetAll
