# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdSetRegmem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdSetRegmem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdSetRegmem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdSetRegmem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdSetRegmem
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdSetRegmem
    def Regmem(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from FB.OdinRegmem import OdinRegmem
            obj = OdinRegmem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CmdSetRegmemStart(builder):
    builder.StartObject(2)

def Start(builder):
    CmdSetRegmemStart(builder)

def CmdSetRegmemAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdSetRegmemAddCoreId(builder, coreId)

def CmdSetRegmemAddRegmem(builder, regmem):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(regmem), 0)

def AddRegmem(builder, regmem):
    CmdSetRegmemAddRegmem(builder, regmem)

def CmdSetRegmemEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdSetRegmemEnd(builder)

import FB.OdinRegmem
try:
    from typing import Optional
except:
    pass

class CmdSetRegmemT(object):

    # CmdSetRegmemT
    def __init__(
        self,
        coreId = 0,
        regmem = None,
    ):
        self.coreId = coreId  # type: int
        self.regmem = regmem  # type: Optional[FB.OdinRegmem.OdinRegmemT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdSetRegmem = CmdSetRegmem()
        cmdSetRegmem.Init(buf, pos)
        return cls.InitFromObj(cmdSetRegmem)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdSetRegmem):
        x = CmdSetRegmemT()
        x._UnPack(cmdSetRegmem)
        return x

    # CmdSetRegmemT
    def _UnPack(self, cmdSetRegmem):
        if cmdSetRegmem is None:
            return
        self.coreId = cmdSetRegmem.CoreId()
        if cmdSetRegmem.Regmem() is not None:
            self.regmem = FB.OdinRegmem.OdinRegmemT.InitFromObj(cmdSetRegmem.Regmem())

    # CmdSetRegmemT
    def Pack(self, builder):
        CmdSetRegmemStart(builder)
        CmdSetRegmemAddCoreId(builder, self.coreId)
        if self.regmem is not None:
            regmem = self.regmem.Pack(builder)
            CmdSetRegmemAddRegmem(builder, regmem)
        cmdSetRegmem = CmdSetRegmemEnd(builder)
        return cmdSetRegmem
