# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdSendPacket(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdSendPacket()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdSendPacket(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdSendPacket
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdSendPacket
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdSendPacket
    def Words(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CmdSendPacket
    def WordsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # CmdSendPacket
    def WordsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CmdSendPacket
    def WordsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def CmdSendPacketStart(builder):
    builder.StartObject(2)

def Start(builder):
    CmdSendPacketStart(builder)

def CmdSendPacketAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdSendPacketAddCoreId(builder, coreId)

def CmdSendPacketAddWords(builder, words):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(words), 0)

def AddWords(builder, words):
    CmdSendPacketAddWords(builder, words)

def CmdSendPacketStartWordsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWordsVector(builder, numElems):
    return CmdSendPacketStartWordsVector(builder, numElems)

def CmdSendPacketCreateWordsVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependUint32(item)
    return builder.EndVector()

def CreateWordsVector(builder, data):
    CmdSendPacketCreateWordsVector(builder, data)

def CmdSendPacketEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdSendPacketEnd(builder)

try:
    from typing import List
except:
    pass

class CmdSendPacketT(object):

    # CmdSendPacketT
    def __init__(
        self,
        coreId = 0,
        words = None,
    ):
        self.coreId = coreId  # type: int
        self.words = words  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdSendPacket = CmdSendPacket()
        cmdSendPacket.Init(buf, pos)
        return cls.InitFromObj(cmdSendPacket)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdSendPacket):
        x = CmdSendPacketT()
        x._UnPack(cmdSendPacket)
        return x

    # CmdSendPacketT
    def _UnPack(self, cmdSendPacket):
        if cmdSendPacket is None:
            return
        self.coreId = cmdSendPacket.CoreId()
        if not cmdSendPacket.WordsIsNone():
            if np is None:
                self.words = []
                for i in range(cmdSendPacket.WordsLength()):
                    self.words.append(cmdSendPacket.Words(i))
            else:
                self.words = cmdSendPacket.WordsAsNumpy()

    # CmdSendPacketT
    def Pack(self, builder):
        if self.words is not None:
            if np is not None and type(self.words) is np.ndarray:
                words = builder.CreateNumpyVector(self.words)
            else:
                CmdSendPacketStartWordsVector(builder, len(self.words))
                for i in reversed(range(len(self.words))):
                    builder.PrependUint32(self.words[i])
                words = builder.EndVector()
        CmdSendPacketStart(builder)
        CmdSendPacketAddCoreId(builder, self.coreId)
        if self.words is not None:
            CmdSendPacketAddWords(builder, words)
        cmdSendPacket = CmdSendPacketEnd(builder)
        return cmdSendPacket
