# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdSetSynapse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdSetSynapse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdSetSynapse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdSetSynapse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdSetSynapse
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdSetSynapse
    def PreNeurId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CmdSetSynapse
    def PostNeurId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CmdSetSynapse
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def CmdSetSynapseStart(builder):
    builder.StartObject(4)

def Start(builder):
    CmdSetSynapseStart(builder)

def CmdSetSynapseAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdSetSynapseAddCoreId(builder, coreId)

def CmdSetSynapseAddPreNeurId(builder, preNeurId):
    builder.PrependUint32Slot(1, preNeurId, 0)

def AddPreNeurId(builder, preNeurId):
    CmdSetSynapseAddPreNeurId(builder, preNeurId)

def CmdSetSynapseAddPostNeurId(builder, postNeurId):
    builder.PrependUint32Slot(2, postNeurId, 0)

def AddPostNeurId(builder, postNeurId):
    CmdSetSynapseAddPostNeurId(builder, postNeurId)

def CmdSetSynapseAddWeight(builder, weight):
    builder.PrependUint8Slot(3, weight, 0)

def AddWeight(builder, weight):
    CmdSetSynapseAddWeight(builder, weight)

def CmdSetSynapseEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdSetSynapseEnd(builder)


class CmdSetSynapseT(object):

    # CmdSetSynapseT
    def __init__(
        self,
        coreId = 0,
        preNeurId = 0,
        postNeurId = 0,
        weight = 0,
    ):
        self.coreId = coreId  # type: int
        self.preNeurId = preNeurId  # type: int
        self.postNeurId = postNeurId  # type: int
        self.weight = weight  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdSetSynapse = CmdSetSynapse()
        cmdSetSynapse.Init(buf, pos)
        return cls.InitFromObj(cmdSetSynapse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdSetSynapse):
        x = CmdSetSynapseT()
        x._UnPack(cmdSetSynapse)
        return x

    # CmdSetSynapseT
    def _UnPack(self, cmdSetSynapse):
        if cmdSetSynapse is None:
            return
        self.coreId = cmdSetSynapse.CoreId()
        self.preNeurId = cmdSetSynapse.PreNeurId()
        self.postNeurId = cmdSetSynapse.PostNeurId()
        self.weight = cmdSetSynapse.Weight()

    # CmdSetSynapseT
    def Pack(self, builder):
        CmdSetSynapseStart(builder)
        CmdSetSynapseAddCoreId(builder, self.coreId)
        CmdSetSynapseAddPreNeurId(builder, self.preNeurId)
        CmdSetSynapseAddPostNeurId(builder, self.postNeurId)
        CmdSetSynapseAddWeight(builder, self.weight)
        cmdSetSynapse = CmdSetSynapseEnd(builder)
        return cmdSetSynapse
