# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdSetNeuron(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdSetNeuron()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdSetNeuron(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdSetNeuron
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdSetNeuron
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdSetNeuron
    def NeurId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CmdSetNeuron
    def NeuronWords(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from FB.NeuronWords128 import NeuronWords128
            obj = NeuronWords128()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CmdSetNeuronStart(builder):
    builder.StartObject(3)

def Start(builder):
    CmdSetNeuronStart(builder)

def CmdSetNeuronAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdSetNeuronAddCoreId(builder, coreId)

def CmdSetNeuronAddNeurId(builder, neurId):
    builder.PrependUint32Slot(1, neurId, 0)

def AddNeurId(builder, neurId):
    CmdSetNeuronAddNeurId(builder, neurId)

def CmdSetNeuronAddNeuronWords(builder, neuronWords):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(neuronWords), 0)

def AddNeuronWords(builder, neuronWords):
    CmdSetNeuronAddNeuronWords(builder, neuronWords)

def CmdSetNeuronEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdSetNeuronEnd(builder)

import FB.NeuronWords128
try:
    from typing import Optional
except:
    pass

class CmdSetNeuronT(object):

    # CmdSetNeuronT
    def __init__(
        self,
        coreId = 0,
        neurId = 0,
        neuronWords = None,
    ):
        self.coreId = coreId  # type: int
        self.neurId = neurId  # type: int
        self.neuronWords = neuronWords  # type: Optional[FB.NeuronWords128.NeuronWords128T]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdSetNeuron = CmdSetNeuron()
        cmdSetNeuron.Init(buf, pos)
        return cls.InitFromObj(cmdSetNeuron)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdSetNeuron):
        x = CmdSetNeuronT()
        x._UnPack(cmdSetNeuron)
        return x

    # CmdSetNeuronT
    def _UnPack(self, cmdSetNeuron):
        if cmdSetNeuron is None:
            return
        self.coreId = cmdSetNeuron.CoreId()
        self.neurId = cmdSetNeuron.NeurId()
        if cmdSetNeuron.NeuronWords() is not None:
            self.neuronWords = FB.NeuronWords128.NeuronWords128T.InitFromObj(cmdSetNeuron.NeuronWords())

    # CmdSetNeuronT
    def Pack(self, builder):
        CmdSetNeuronStart(builder)
        CmdSetNeuronAddCoreId(builder, self.coreId)
        CmdSetNeuronAddNeurId(builder, self.neurId)
        if self.neuronWords is not None:
            neuronWords = self.neuronWords.Pack(builder)
            CmdSetNeuronAddNeuronWords(builder, neuronWords)
        cmdSetNeuron = CmdSetNeuronEnd(builder)
        return cmdSetNeuron
