# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdSetServerOutput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdSetServerOutput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdSetServerOutput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdSetServerOutput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdSetServerOutput
    def FromCore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdSetServerOutput
    def FromNeur(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CmdSetServerOutput
    def ServerOutput(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def CmdSetServerOutputStart(builder):
    builder.StartObject(3)

def Start(builder):
    CmdSetServerOutputStart(builder)

def CmdSetServerOutputAddFromCore(builder, fromCore):
    builder.PrependUint8Slot(0, fromCore, 0)

def AddFromCore(builder, fromCore):
    CmdSetServerOutputAddFromCore(builder, fromCore)

def CmdSetServerOutputAddFromNeur(builder, fromNeur):
    builder.PrependUint8Slot(1, fromNeur, 0)

def AddFromNeur(builder, fromNeur):
    CmdSetServerOutputAddFromNeur(builder, fromNeur)

def CmdSetServerOutputAddServerOutput(builder, serverOutput):
    builder.PrependBoolSlot(2, serverOutput, 0)

def AddServerOutput(builder, serverOutput):
    CmdSetServerOutputAddServerOutput(builder, serverOutput)

def CmdSetServerOutputEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdSetServerOutputEnd(builder)


class CmdSetServerOutputT(object):

    # CmdSetServerOutputT
    def __init__(
        self,
        fromCore = 0,
        fromNeur = 0,
        serverOutput = False,
    ):
        self.fromCore = fromCore  # type: int
        self.fromNeur = fromNeur  # type: int
        self.serverOutput = serverOutput  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdSetServerOutput = CmdSetServerOutput()
        cmdSetServerOutput.Init(buf, pos)
        return cls.InitFromObj(cmdSetServerOutput)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdSetServerOutput):
        x = CmdSetServerOutputT()
        x._UnPack(cmdSetServerOutput)
        return x

    # CmdSetServerOutputT
    def _UnPack(self, cmdSetServerOutput):
        if cmdSetServerOutput is None:
            return
        self.fromCore = cmdSetServerOutput.FromCore()
        self.fromNeur = cmdSetServerOutput.FromNeur()
        self.serverOutput = cmdSetServerOutput.ServerOutput()

    # CmdSetServerOutputT
    def Pack(self, builder):
        CmdSetServerOutputStart(builder)
        CmdSetServerOutputAddFromCore(builder, self.fromCore)
        CmdSetServerOutputAddFromNeur(builder, self.fromNeur)
        CmdSetServerOutputAddServerOutput(builder, self.serverOutput)
        cmdSetServerOutput = CmdSetServerOutputEnd(builder)
        return cmdSetServerOutput
