# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdWaitOdinCore(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdWaitOdinCore()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdWaitOdinCore(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdWaitOdinCore
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdWaitOdinCore
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def CmdWaitOdinCoreStart(builder):
    builder.StartObject(1)

def Start(builder):
    CmdWaitOdinCoreStart(builder)

def CmdWaitOdinCoreAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    CmdWaitOdinCoreAddCoreId(builder, coreId)

def CmdWaitOdinCoreEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdWaitOdinCoreEnd(builder)


class CmdWaitOdinCoreT(object):

    # CmdWaitOdinCoreT
    def __init__(
        self,
        coreId = 0,
    ):
        self.coreId = coreId  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdWaitOdinCore = CmdWaitOdinCore()
        cmdWaitOdinCore.Init(buf, pos)
        return cls.InitFromObj(cmdWaitOdinCore)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cmdWaitOdinCore):
        x = CmdWaitOdinCoreT()
        x._UnPack(cmdWaitOdinCore)
        return x

    # CmdWaitOdinCoreT
    def _UnPack(self, cmdWaitOdinCore):
        if cmdWaitOdinCore is None:
            return
        self.coreId = cmdWaitOdinCore.CoreId()

    # CmdWaitOdinCoreT
    def Pack(self, builder):
        CmdWaitOdinCoreStart(builder)
        CmdWaitOdinCoreAddCoreId(builder, self.coreId)
        cmdWaitOdinCore = CmdWaitOdinCoreEnd(builder)
        return cmdWaitOdinCore
