# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Input(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Input()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Input
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Input
    def Commands(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FB.Cmd import Cmd
            obj = Cmd()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Input
    def CommandsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Input
    def CommandsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def InputStart(builder):
    builder.StartObject(1)

def Start(builder):
    InputStart(builder)

def InputAddCommands(builder, commands):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(commands), 0)

def AddCommands(builder, commands):
    InputAddCommands(builder, commands)

def InputStartCommandsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCommandsVector(builder, numElems):
    return InputStartCommandsVector(builder, numElems)

def InputCreateCommandsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateCommandsVector(builder, data):
    InputCreateCommandsVector(builder, data)

def InputEnd(builder):
    return builder.EndObject()

def End(builder):
    return InputEnd(builder)

import FB.Cmd
try:
    from typing import List
except:
    pass

class InputT(object):

    # InputT
    def __init__(
        self,
        commands = None,
    ):
        self.commands = commands  # type: Optional[List[FB.Cmd.CmdT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        input = Input()
        input.Init(buf, pos)
        return cls.InitFromObj(input)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, input):
        x = InputT()
        x._UnPack(input)
        return x

    # InputT
    def _UnPack(self, input):
        if input is None:
            return
        if not input.CommandsIsNone():
            self.commands = []
            for i in range(input.CommandsLength()):
                if input.Commands(i) is None:
                    self.commands.append(None)
                else:
                    cmd_ = FB.Cmd.CmdT.InitFromObj(input.Commands(i))
                    self.commands.append(cmd_)

    # InputT
    def Pack(self, builder):
        if self.commands is not None:
            commandslist = []
            for i in range(len(self.commands)):
                commandslist.append(self.commands[i].Pack(builder))
            InputStartCommandsVector(builder, len(self.commands))
            for i in reversed(range(len(self.commands))):
                builder.PrependUOffsetTRelative(commandslist[i])
            commands = builder.EndVector()
        InputStart(builder)
        if self.commands is not None:
            InputAddCommands(builder, commands)
        input = InputEnd(builder)
        return input
