# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Message(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Message()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Message
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Message
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Message
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MessageStart(builder):
    builder.StartObject(2)

def Start(builder):
    MessageStart(builder)

def MessageAddType(builder, type):
    builder.PrependUint8Slot(0, type, 0)

def AddType(builder, type):
    MessageAddType(builder, type)

def MessageAddText(builder, text):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)

def AddText(builder, text):
    MessageAddText(builder, text)

def MessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return MessageEnd(builder)


class MessageT(object):

    # MessageT
    def __init__(
        self,
        type = 0,
        text = None,
    ):
        self.type = type  # type: int
        self.text = text  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        message = Message()
        message.Init(buf, pos)
        return cls.InitFromObj(message)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, message):
        x = MessageT()
        x._UnPack(message)
        return x

    # MessageT
    def _UnPack(self, message):
        if message is None:
            return
        self.type = message.Type()
        self.text = message.Text()

    # MessageT
    def Pack(self, builder):
        if self.text is not None:
            text = builder.CreateString(self.text)
        MessageStart(builder)
        MessageAddType(builder, self.type)
        if self.text is not None:
            MessageAddText(builder, text)
        message = MessageEnd(builder)
        return message
