# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NeuronWords128(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # NeuronWords128
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NeuronWords128
    def Words(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 4)) for i in range(self.WordsLength())]
        elif j >= 0 and j < self.WordsLength():
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + j * 4))
        else:
            return None

    # NeuronWords128
    def WordsAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Uint32Flags, self._tab.Pos + 0, self.WordsLength())

    # NeuronWords128
    def WordsLength(self):
        return 4

    # NeuronWords128
    def WordsIsNone(self):
        return False


def CreateNeuronWords128(builder, words):
    builder.Prep(4, 16)
    for _idx0 in range(4 , 0, -1):
        builder.PrependUint32(words[_idx0-1])
    return builder.Offset()

try:
    from typing import List
except:
    pass

class NeuronWords128T(object):

    # NeuronWords128T
    def __init__(
        self,
        words = None,
    ):
        self.words = words  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        neuronWords128 = NeuronWords128()
        neuronWords128.Init(buf, pos)
        return cls.InitFromObj(neuronWords128)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, neuronWords128):
        x = NeuronWords128T()
        x._UnPack(neuronWords128)
        return x

    # NeuronWords128T
    def _UnPack(self, neuronWords128):
        if neuronWords128 is None:
            return
        if not neuronWords128.WordsIsNone():
            if np is None:
                self.words = []
                for i in range(neuronWords128.WordsLength()):
                    self.words.append(neuronWords128.Words(i))
            else:
                self.words = neuronWords128.WordsAsNumpy()

    # NeuronWords128T
    def Pack(self, builder):
        return CreateNeuronWords128(builder, self.words)
