# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OdinRegmem(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 100

    # OdinRegmem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OdinRegmem
    def OpenLoop(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # OdinRegmem
    def SynSign(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4 + i * 4)) for i in range(self.SynSignLength())]
        elif j >= 0 and j < self.SynSignLength():
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4 + j * 4))
        else:
            return None

    # OdinRegmem
    def SynSignAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Uint32Flags, self._tab.Pos + 4, self.SynSignLength())

    # OdinRegmem
    def SynSignLength(self):
        return 8

    # OdinRegmem
    def SynSignIsNone(self):
        return False

    # OdinRegmem
    def ReservedSynSign(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(36 + i * 4)) for i in range(self.ReservedSynSignLength())]
        elif j >= 0 and j < self.ReservedSynSignLength():
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(36 + j * 4))
        else:
            return None

    # OdinRegmem
    def ReservedSynSignAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Uint32Flags, self._tab.Pos + 36, self.ReservedSynSignLength())

    # OdinRegmem
    def ReservedSynSignLength(self):
        return 8

    # OdinRegmem
    def ReservedSynSignIsNone(self):
        return False

    # OdinRegmem
    def BurstTimeref(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(68))
    # OdinRegmem
    def AerSrcCtrlNneur(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(72))
    # OdinRegmem
    def OutAerMonitorEn(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(76))
    # OdinRegmem
    def MonitorNeurAddr(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(80))
    # OdinRegmem
    def MonitorSynAddr(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(84))
    # OdinRegmem
    def UpdateUnmappedSyn(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(88))
    # OdinRegmem
    def PropagateUnmappedSyn(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(92))
    # OdinRegmem
    def SdspOnSynStim(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(96))

def CreateOdinRegmem(builder, openLoop, synSign, reservedSynSign, burstTimeref, aerSrcCtrlNneur, outAerMonitorEn, monitorNeurAddr, monitorSynAddr, updateUnmappedSyn, propagateUnmappedSyn, sdspOnSynStim):
    builder.Prep(4, 100)
    builder.PrependUint32(sdspOnSynStim)
    builder.PrependUint32(propagateUnmappedSyn)
    builder.PrependUint32(updateUnmappedSyn)
    builder.PrependUint32(monitorSynAddr)
    builder.PrependUint32(monitorNeurAddr)
    builder.PrependUint32(outAerMonitorEn)
    builder.PrependUint32(aerSrcCtrlNneur)
    builder.PrependUint32(burstTimeref)
    for _idx0 in range(8 , 0, -1):
        builder.PrependUint32(reservedSynSign[_idx0-1])
    for _idx0 in range(8 , 0, -1):
        builder.PrependUint32(synSign[_idx0-1])
    builder.PrependUint32(openLoop)
    return builder.Offset()

try:
    from typing import List
except:
    pass

class OdinRegmemT(object):

    # OdinRegmemT
    def __init__(
        self,
        openLoop = 0,
        synSign = None,
        reservedSynSign = None,
        burstTimeref = 0,
        aerSrcCtrlNneur = 0,
        outAerMonitorEn = 0,
        monitorNeurAddr = 0,
        monitorSynAddr = 0,
        updateUnmappedSyn = 0,
        propagateUnmappedSyn = 0,
        sdspOnSynStim = 0,
    ):
        self.openLoop = openLoop  # type: int
        self.synSign = synSign  # type: Optional[List[int]]
        self.reservedSynSign = reservedSynSign  # type: Optional[List[int]]
        self.burstTimeref = burstTimeref  # type: int
        self.aerSrcCtrlNneur = aerSrcCtrlNneur  # type: int
        self.outAerMonitorEn = outAerMonitorEn  # type: int
        self.monitorNeurAddr = monitorNeurAddr  # type: int
        self.monitorSynAddr = monitorSynAddr  # type: int
        self.updateUnmappedSyn = updateUnmappedSyn  # type: int
        self.propagateUnmappedSyn = propagateUnmappedSyn  # type: int
        self.sdspOnSynStim = sdspOnSynStim  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        odinRegmem = OdinRegmem()
        odinRegmem.Init(buf, pos)
        return cls.InitFromObj(odinRegmem)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, odinRegmem):
        x = OdinRegmemT()
        x._UnPack(odinRegmem)
        return x

    # OdinRegmemT
    def _UnPack(self, odinRegmem):
        if odinRegmem is None:
            return
        self.openLoop = odinRegmem.OpenLoop()
        if not odinRegmem.SynSignIsNone():
            if np is None:
                self.synSign = []
                for i in range(odinRegmem.SynSignLength()):
                    self.synSign.append(odinRegmem.SynSign(i))
            else:
                self.synSign = odinRegmem.SynSignAsNumpy()
        if not odinRegmem.ReservedSynSignIsNone():
            if np is None:
                self.reservedSynSign = []
                for i in range(odinRegmem.ReservedSynSignLength()):
                    self.reservedSynSign.append(odinRegmem.ReservedSynSign(i))
            else:
                self.reservedSynSign = odinRegmem.ReservedSynSignAsNumpy()
        self.burstTimeref = odinRegmem.BurstTimeref()
        self.aerSrcCtrlNneur = odinRegmem.AerSrcCtrlNneur()
        self.outAerMonitorEn = odinRegmem.OutAerMonitorEn()
        self.monitorNeurAddr = odinRegmem.MonitorNeurAddr()
        self.monitorSynAddr = odinRegmem.MonitorSynAddr()
        self.updateUnmappedSyn = odinRegmem.UpdateUnmappedSyn()
        self.propagateUnmappedSyn = odinRegmem.PropagateUnmappedSyn()
        self.sdspOnSynStim = odinRegmem.SdspOnSynStim()

    # OdinRegmemT
    def Pack(self, builder):
        return CreateOdinRegmem(builder, self.openLoop, self.synSign, self.reservedSynSign, self.burstTimeref, self.aerSrcCtrlNneur, self.outAerMonitorEn, self.monitorNeurAddr, self.monitorSynAddr, self.updateUnmappedSyn, self.propagateUnmappedSyn, self.sdspOnSynStim)
