# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Output(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Output()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOutput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Output
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Output
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from FB.Message import Message
            obj = Message()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Output
    def Spikes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from FB.Spikes import Spikes
            obj = Spikes()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Output
    def CmdOutput(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from FB.CmdOutput import CmdOutput
            obj = CmdOutput()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def OutputStart(builder):
    builder.StartObject(3)

def Start(builder):
    OutputStart(builder)

def OutputAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    OutputAddMessage(builder, message)

def OutputAddSpikes(builder, spikes):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spikes), 0)

def AddSpikes(builder, spikes):
    OutputAddSpikes(builder, spikes)

def OutputAddCmdOutput(builder, cmdOutput):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(cmdOutput), 0)

def AddCmdOutput(builder, cmdOutput):
    OutputAddCmdOutput(builder, cmdOutput)

def OutputEnd(builder):
    return builder.EndObject()

def End(builder):
    return OutputEnd(builder)

import FB.CmdOutput
import FB.Message
import FB.Spikes
try:
    from typing import Optional
except:
    pass

class OutputT(object):

    # OutputT
    def __init__(
        self,
        message = None,
        spikes = None,
        cmdOutput = None,
    ):
        self.message = message  # type: Optional[FB.Message.MessageT]
        self.spikes = spikes  # type: Optional[FB.Spikes.SpikesT]
        self.cmdOutput = cmdOutput  # type: Optional[FB.CmdOutput.CmdOutputT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        output = Output()
        output.Init(buf, pos)
        return cls.InitFromObj(output)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, output):
        x = OutputT()
        x._UnPack(output)
        return x

    # OutputT
    def _UnPack(self, output):
        if output is None:
            return
        if output.Message() is not None:
            self.message = FB.Message.MessageT.InitFromObj(output.Message())
        if output.Spikes() is not None:
            self.spikes = FB.Spikes.SpikesT.InitFromObj(output.Spikes())
        if output.CmdOutput() is not None:
            self.cmdOutput = FB.CmdOutput.CmdOutputT.InitFromObj(output.CmdOutput())

    # OutputT
    def Pack(self, builder):
        if self.message is not None:
            message = self.message.Pack(builder)
        if self.spikes is not None:
            spikes = self.spikes.Pack(builder)
        if self.cmdOutput is not None:
            cmdOutput = self.cmdOutput.Pack(builder)
        OutputStart(builder)
        if self.message is not None:
            OutputAddMessage(builder, message)
        if self.spikes is not None:
            OutputAddSpikes(builder, spikes)
        if self.cmdOutput is not None:
            OutputAddCmdOutput(builder, cmdOutput)
        output = OutputEnd(builder)
        return output
