# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Spikes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Spikes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpikes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Spikes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Spikes
    def CoreId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Spikes
    def Words(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Spikes
    def WordsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Spikes
    def WordsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Spikes
    def WordsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def SpikesStart(builder):
    builder.StartObject(2)

def Start(builder):
    SpikesStart(builder)

def SpikesAddCoreId(builder, coreId):
    builder.PrependUint8Slot(0, coreId, 0)

def AddCoreId(builder, coreId):
    SpikesAddCoreId(builder, coreId)

def SpikesAddWords(builder, words):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(words), 0)

def AddWords(builder, words):
    SpikesAddWords(builder, words)

def SpikesStartWordsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartWordsVector(builder, numElems):
    return SpikesStartWordsVector(builder, numElems)

def SpikesCreateWordsVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateWordsVector(builder, data):
    SpikesCreateWordsVector(builder, data)

def SpikesEnd(builder):
    return builder.EndObject()

def End(builder):
    return SpikesEnd(builder)

try:
    from typing import List
except:
    pass

class SpikesT(object):

    # SpikesT
    def __init__(
        self,
        coreId = 0,
        words = None,
    ):
        self.coreId = coreId  # type: int
        self.words = words  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        spikes = Spikes()
        spikes.Init(buf, pos)
        return cls.InitFromObj(spikes)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, spikes):
        x = SpikesT()
        x._UnPack(spikes)
        return x

    # SpikesT
    def _UnPack(self, spikes):
        if spikes is None:
            return
        self.coreId = spikes.CoreId()
        if not spikes.WordsIsNone():
            if np is None:
                self.words = []
                for i in range(spikes.WordsLength()):
                    self.words.append(spikes.Words(i))
            else:
                self.words = spikes.WordsAsNumpy()

    # SpikesT
    def Pack(self, builder):
        if self.words is not None:
            if np is not None and type(self.words) is np.ndarray:
                words = builder.CreateNumpyVector(self.words)
            else:
                SpikesStartWordsVector(builder, len(self.words))
                for i in reversed(range(len(self.words))):
                    builder.PrependUint8(self.words[i])
                words = builder.EndVector()
        SpikesStart(builder)
        SpikesAddCoreId(builder, self.coreId)
        if self.words is not None:
            SpikesAddWords(builder, words)
        spikes = SpikesEnd(builder)
        return spikes
