// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CMD_FB_H_
#define FLATBUFFERS_GENERATED_CMD_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "odin_types_generated.h"

namespace FB {

struct CmdResetAll;
struct CmdResetAllBuilder;
struct CmdResetAllT;

struct CmdResetOdinCore;
struct CmdResetOdinCoreBuilder;
struct CmdResetOdinCoreT;

struct CmdWaitIdle;
struct CmdWaitIdleBuilder;
struct CmdWaitIdleT;

struct CmdWaitOdinCore;
struct CmdWaitOdinCoreBuilder;
struct CmdWaitOdinCoreT;

struct CmdSendPacket;
struct CmdSendPacketBuilder;
struct CmdSendPacketT;

struct CmdGetRegmem;
struct CmdGetRegmemBuilder;
struct CmdGetRegmemT;

struct CmdSetRegmem;
struct CmdSetRegmemBuilder;
struct CmdSetRegmemT;

struct CmdGetNeuron;
struct CmdGetNeuronBuilder;
struct CmdGetNeuronT;

struct CmdSetNeuron;
struct CmdSetNeuronBuilder;
struct CmdSetNeuronT;

struct CmdGetSynapse;
struct CmdGetSynapseBuilder;
struct CmdGetSynapseT;

struct CmdSetSynapse;
struct CmdSetSynapseBuilder;
struct CmdSetSynapseT;

struct CmdResetRouter;
struct CmdResetRouterBuilder;
struct CmdResetRouterT;

struct CmdAddRoute;
struct CmdAddRouteBuilder;
struct CmdAddRouteT;

struct CmdSetServerOutput;
struct CmdSetServerOutputBuilder;
struct CmdSetServerOutputT;

struct Cmd;
struct CmdBuilder;
struct CmdT;

enum Cmd_t : uint8_t {
  Cmd_t_NONE = 0,
  Cmd_t_CmdResetAll = 1,
  Cmd_t_CmdResetOdinCore = 2,
  Cmd_t_CmdWaitIdle = 3,
  Cmd_t_CmdWaitOdinCore = 4,
  Cmd_t_CmdSendPacket = 5,
  Cmd_t_CmdGetRegmem = 6,
  Cmd_t_CmdSetRegmem = 7,
  Cmd_t_CmdGetNeuron = 8,
  Cmd_t_CmdSetNeuron = 9,
  Cmd_t_CmdGetSynapse = 10,
  Cmd_t_CmdSetSynapse = 11,
  Cmd_t_CmdResetRouter = 12,
  Cmd_t_CmdAddRoute = 13,
  Cmd_t_CmdSetServerOutput = 14,
  Cmd_t_MIN = Cmd_t_NONE,
  Cmd_t_MAX = Cmd_t_CmdSetServerOutput
};

inline const Cmd_t (&EnumValuesCmd_t())[15] {
  static const Cmd_t values[] = {
    Cmd_t_NONE,
    Cmd_t_CmdResetAll,
    Cmd_t_CmdResetOdinCore,
    Cmd_t_CmdWaitIdle,
    Cmd_t_CmdWaitOdinCore,
    Cmd_t_CmdSendPacket,
    Cmd_t_CmdGetRegmem,
    Cmd_t_CmdSetRegmem,
    Cmd_t_CmdGetNeuron,
    Cmd_t_CmdSetNeuron,
    Cmd_t_CmdGetSynapse,
    Cmd_t_CmdSetSynapse,
    Cmd_t_CmdResetRouter,
    Cmd_t_CmdAddRoute,
    Cmd_t_CmdSetServerOutput
  };
  return values;
}

inline const char * const *EnumNamesCmd_t() {
  static const char * const names[16] = {
    "NONE",
    "CmdResetAll",
    "CmdResetOdinCore",
    "CmdWaitIdle",
    "CmdWaitOdinCore",
    "CmdSendPacket",
    "CmdGetRegmem",
    "CmdSetRegmem",
    "CmdGetNeuron",
    "CmdSetNeuron",
    "CmdGetSynapse",
    "CmdSetSynapse",
    "CmdResetRouter",
    "CmdAddRoute",
    "CmdSetServerOutput",
    nullptr
  };
  return names;
}

inline const char *EnumNameCmd_t(Cmd_t e) {
  if (::flatbuffers::IsOutRange(e, Cmd_t_NONE, Cmd_t_CmdSetServerOutput)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCmd_t()[index];
}

template<typename T> struct Cmd_tTraits {
  static const Cmd_t enum_value = Cmd_t_NONE;
};

template<> struct Cmd_tTraits<FB::CmdResetAll> {
  static const Cmd_t enum_value = Cmd_t_CmdResetAll;
};

template<> struct Cmd_tTraits<FB::CmdResetOdinCore> {
  static const Cmd_t enum_value = Cmd_t_CmdResetOdinCore;
};

template<> struct Cmd_tTraits<FB::CmdWaitIdle> {
  static const Cmd_t enum_value = Cmd_t_CmdWaitIdle;
};

template<> struct Cmd_tTraits<FB::CmdWaitOdinCore> {
  static const Cmd_t enum_value = Cmd_t_CmdWaitOdinCore;
};

template<> struct Cmd_tTraits<FB::CmdSendPacket> {
  static const Cmd_t enum_value = Cmd_t_CmdSendPacket;
};

template<> struct Cmd_tTraits<FB::CmdGetRegmem> {
  static const Cmd_t enum_value = Cmd_t_CmdGetRegmem;
};

template<> struct Cmd_tTraits<FB::CmdSetRegmem> {
  static const Cmd_t enum_value = Cmd_t_CmdSetRegmem;
};

template<> struct Cmd_tTraits<FB::CmdGetNeuron> {
  static const Cmd_t enum_value = Cmd_t_CmdGetNeuron;
};

template<> struct Cmd_tTraits<FB::CmdSetNeuron> {
  static const Cmd_t enum_value = Cmd_t_CmdSetNeuron;
};

template<> struct Cmd_tTraits<FB::CmdGetSynapse> {
  static const Cmd_t enum_value = Cmd_t_CmdGetSynapse;
};

template<> struct Cmd_tTraits<FB::CmdSetSynapse> {
  static const Cmd_t enum_value = Cmd_t_CmdSetSynapse;
};

template<> struct Cmd_tTraits<FB::CmdResetRouter> {
  static const Cmd_t enum_value = Cmd_t_CmdResetRouter;
};

template<> struct Cmd_tTraits<FB::CmdAddRoute> {
  static const Cmd_t enum_value = Cmd_t_CmdAddRoute;
};

template<> struct Cmd_tTraits<FB::CmdSetServerOutput> {
  static const Cmd_t enum_value = Cmd_t_CmdSetServerOutput;
};

template<typename T> struct Cmd_tUnionTraits {
  static const Cmd_t enum_value = Cmd_t_NONE;
};

template<> struct Cmd_tUnionTraits<FB::CmdResetAllT> {
  static const Cmd_t enum_value = Cmd_t_CmdResetAll;
};

template<> struct Cmd_tUnionTraits<FB::CmdResetOdinCoreT> {
  static const Cmd_t enum_value = Cmd_t_CmdResetOdinCore;
};

template<> struct Cmd_tUnionTraits<FB::CmdWaitIdleT> {
  static const Cmd_t enum_value = Cmd_t_CmdWaitIdle;
};

template<> struct Cmd_tUnionTraits<FB::CmdWaitOdinCoreT> {
  static const Cmd_t enum_value = Cmd_t_CmdWaitOdinCore;
};

template<> struct Cmd_tUnionTraits<FB::CmdSendPacketT> {
  static const Cmd_t enum_value = Cmd_t_CmdSendPacket;
};

template<> struct Cmd_tUnionTraits<FB::CmdGetRegmemT> {
  static const Cmd_t enum_value = Cmd_t_CmdGetRegmem;
};

template<> struct Cmd_tUnionTraits<FB::CmdSetRegmemT> {
  static const Cmd_t enum_value = Cmd_t_CmdSetRegmem;
};

template<> struct Cmd_tUnionTraits<FB::CmdGetNeuronT> {
  static const Cmd_t enum_value = Cmd_t_CmdGetNeuron;
};

template<> struct Cmd_tUnionTraits<FB::CmdSetNeuronT> {
  static const Cmd_t enum_value = Cmd_t_CmdSetNeuron;
};

template<> struct Cmd_tUnionTraits<FB::CmdGetSynapseT> {
  static const Cmd_t enum_value = Cmd_t_CmdGetSynapse;
};

template<> struct Cmd_tUnionTraits<FB::CmdSetSynapseT> {
  static const Cmd_t enum_value = Cmd_t_CmdSetSynapse;
};

template<> struct Cmd_tUnionTraits<FB::CmdResetRouterT> {
  static const Cmd_t enum_value = Cmd_t_CmdResetRouter;
};

template<> struct Cmd_tUnionTraits<FB::CmdAddRouteT> {
  static const Cmd_t enum_value = Cmd_t_CmdAddRoute;
};

template<> struct Cmd_tUnionTraits<FB::CmdSetServerOutputT> {
  static const Cmd_t enum_value = Cmd_t_CmdSetServerOutput;
};

struct Cmd_tUnion {
  Cmd_t type;
  void *value;

  Cmd_tUnion() : type(Cmd_t_NONE), value(nullptr) {}
  Cmd_tUnion(Cmd_tUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Cmd_t_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  Cmd_tUnion(const Cmd_tUnion &);
  Cmd_tUnion &operator=(const Cmd_tUnion &u)
    { Cmd_tUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  Cmd_tUnion &operator=(Cmd_tUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~Cmd_tUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = Cmd_tUnionTraits<RT>::enum_value;
    if (type != Cmd_t_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, Cmd_t type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  FB::CmdResetAllT *AsCmdResetAll() {
    return type == Cmd_t_CmdResetAll ?
      reinterpret_cast<FB::CmdResetAllT *>(value) : nullptr;
  }
  const FB::CmdResetAllT *AsCmdResetAll() const {
    return type == Cmd_t_CmdResetAll ?
      reinterpret_cast<const FB::CmdResetAllT *>(value) : nullptr;
  }
  FB::CmdResetOdinCoreT *AsCmdResetOdinCore() {
    return type == Cmd_t_CmdResetOdinCore ?
      reinterpret_cast<FB::CmdResetOdinCoreT *>(value) : nullptr;
  }
  const FB::CmdResetOdinCoreT *AsCmdResetOdinCore() const {
    return type == Cmd_t_CmdResetOdinCore ?
      reinterpret_cast<const FB::CmdResetOdinCoreT *>(value) : nullptr;
  }
  FB::CmdWaitIdleT *AsCmdWaitIdle() {
    return type == Cmd_t_CmdWaitIdle ?
      reinterpret_cast<FB::CmdWaitIdleT *>(value) : nullptr;
  }
  const FB::CmdWaitIdleT *AsCmdWaitIdle() const {
    return type == Cmd_t_CmdWaitIdle ?
      reinterpret_cast<const FB::CmdWaitIdleT *>(value) : nullptr;
  }
  FB::CmdWaitOdinCoreT *AsCmdWaitOdinCore() {
    return type == Cmd_t_CmdWaitOdinCore ?
      reinterpret_cast<FB::CmdWaitOdinCoreT *>(value) : nullptr;
  }
  const FB::CmdWaitOdinCoreT *AsCmdWaitOdinCore() const {
    return type == Cmd_t_CmdWaitOdinCore ?
      reinterpret_cast<const FB::CmdWaitOdinCoreT *>(value) : nullptr;
  }
  FB::CmdSendPacketT *AsCmdSendPacket() {
    return type == Cmd_t_CmdSendPacket ?
      reinterpret_cast<FB::CmdSendPacketT *>(value) : nullptr;
  }
  const FB::CmdSendPacketT *AsCmdSendPacket() const {
    return type == Cmd_t_CmdSendPacket ?
      reinterpret_cast<const FB::CmdSendPacketT *>(value) : nullptr;
  }
  FB::CmdGetRegmemT *AsCmdGetRegmem() {
    return type == Cmd_t_CmdGetRegmem ?
      reinterpret_cast<FB::CmdGetRegmemT *>(value) : nullptr;
  }
  const FB::CmdGetRegmemT *AsCmdGetRegmem() const {
    return type == Cmd_t_CmdGetRegmem ?
      reinterpret_cast<const FB::CmdGetRegmemT *>(value) : nullptr;
  }
  FB::CmdSetRegmemT *AsCmdSetRegmem() {
    return type == Cmd_t_CmdSetRegmem ?
      reinterpret_cast<FB::CmdSetRegmemT *>(value) : nullptr;
  }
  const FB::CmdSetRegmemT *AsCmdSetRegmem() const {
    return type == Cmd_t_CmdSetRegmem ?
      reinterpret_cast<const FB::CmdSetRegmemT *>(value) : nullptr;
  }
  FB::CmdGetNeuronT *AsCmdGetNeuron() {
    return type == Cmd_t_CmdGetNeuron ?
      reinterpret_cast<FB::CmdGetNeuronT *>(value) : nullptr;
  }
  const FB::CmdGetNeuronT *AsCmdGetNeuron() const {
    return type == Cmd_t_CmdGetNeuron ?
      reinterpret_cast<const FB::CmdGetNeuronT *>(value) : nullptr;
  }
  FB::CmdSetNeuronT *AsCmdSetNeuron() {
    return type == Cmd_t_CmdSetNeuron ?
      reinterpret_cast<FB::CmdSetNeuronT *>(value) : nullptr;
  }
  const FB::CmdSetNeuronT *AsCmdSetNeuron() const {
    return type == Cmd_t_CmdSetNeuron ?
      reinterpret_cast<const FB::CmdSetNeuronT *>(value) : nullptr;
  }
  FB::CmdGetSynapseT *AsCmdGetSynapse() {
    return type == Cmd_t_CmdGetSynapse ?
      reinterpret_cast<FB::CmdGetSynapseT *>(value) : nullptr;
  }
  const FB::CmdGetSynapseT *AsCmdGetSynapse() const {
    return type == Cmd_t_CmdGetSynapse ?
      reinterpret_cast<const FB::CmdGetSynapseT *>(value) : nullptr;
  }
  FB::CmdSetSynapseT *AsCmdSetSynapse() {
    return type == Cmd_t_CmdSetSynapse ?
      reinterpret_cast<FB::CmdSetSynapseT *>(value) : nullptr;
  }
  const FB::CmdSetSynapseT *AsCmdSetSynapse() const {
    return type == Cmd_t_CmdSetSynapse ?
      reinterpret_cast<const FB::CmdSetSynapseT *>(value) : nullptr;
  }
  FB::CmdResetRouterT *AsCmdResetRouter() {
    return type == Cmd_t_CmdResetRouter ?
      reinterpret_cast<FB::CmdResetRouterT *>(value) : nullptr;
  }
  const FB::CmdResetRouterT *AsCmdResetRouter() const {
    return type == Cmd_t_CmdResetRouter ?
      reinterpret_cast<const FB::CmdResetRouterT *>(value) : nullptr;
  }
  FB::CmdAddRouteT *AsCmdAddRoute() {
    return type == Cmd_t_CmdAddRoute ?
      reinterpret_cast<FB::CmdAddRouteT *>(value) : nullptr;
  }
  const FB::CmdAddRouteT *AsCmdAddRoute() const {
    return type == Cmd_t_CmdAddRoute ?
      reinterpret_cast<const FB::CmdAddRouteT *>(value) : nullptr;
  }
  FB::CmdSetServerOutputT *AsCmdSetServerOutput() {
    return type == Cmd_t_CmdSetServerOutput ?
      reinterpret_cast<FB::CmdSetServerOutputT *>(value) : nullptr;
  }
  const FB::CmdSetServerOutputT *AsCmdSetServerOutput() const {
    return type == Cmd_t_CmdSetServerOutput ?
      reinterpret_cast<const FB::CmdSetServerOutputT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyCmd_t(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Cmd_t type);
template <bool B = false>
bool VerifyCmd_tVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct CmdResetAllT : public ::flatbuffers::NativeTable {
  typedef CmdResetAll TableType;
};

struct CmdResetAll FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdResetAllT NativeTableType;
  typedef CmdResetAllBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  CmdResetAllT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdResetAllT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdResetAll> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetAllT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdResetAllBuilder {
  typedef CmdResetAll Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit CmdResetAllBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdResetAll> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdResetAll>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdResetAll> CreateCmdResetAll(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  CmdResetAllBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdResetAll> CreateCmdResetAll(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetAllT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdResetOdinCoreT : public ::flatbuffers::NativeTable {
  typedef CmdResetOdinCore TableType;
  uint8_t core_id = 0;
};

struct CmdResetOdinCore FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdResetOdinCoreT NativeTableType;
  typedef CmdResetOdinCoreBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           verifier.EndTable();
  }
  CmdResetOdinCoreT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdResetOdinCoreT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdResetOdinCore> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetOdinCoreT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdResetOdinCoreBuilder {
  typedef CmdResetOdinCore Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdResetOdinCore::VT_CORE_ID, core_id, 0);
  }
  explicit CmdResetOdinCoreBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdResetOdinCore> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdResetOdinCore>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdResetOdinCore> CreateCmdResetOdinCore(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0) {
  CmdResetOdinCoreBuilder builder_(_fbb);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdResetOdinCore> CreateCmdResetOdinCore(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetOdinCoreT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdWaitIdleT : public ::flatbuffers::NativeTable {
  typedef CmdWaitIdle TableType;
};

struct CmdWaitIdle FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdWaitIdleT NativeTableType;
  typedef CmdWaitIdleBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  CmdWaitIdleT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdWaitIdleT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdWaitIdle> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdWaitIdleT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdWaitIdleBuilder {
  typedef CmdWaitIdle Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit CmdWaitIdleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdWaitIdle> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdWaitIdle>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdWaitIdle> CreateCmdWaitIdle(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  CmdWaitIdleBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdWaitIdle> CreateCmdWaitIdle(::flatbuffers::FlatBufferBuilder &_fbb, const CmdWaitIdleT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdWaitOdinCoreT : public ::flatbuffers::NativeTable {
  typedef CmdWaitOdinCore TableType;
  uint8_t core_id = 0;
};

struct CmdWaitOdinCore FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdWaitOdinCoreT NativeTableType;
  typedef CmdWaitOdinCoreBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           verifier.EndTable();
  }
  CmdWaitOdinCoreT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdWaitOdinCoreT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdWaitOdinCore> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdWaitOdinCoreT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdWaitOdinCoreBuilder {
  typedef CmdWaitOdinCore Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdWaitOdinCore::VT_CORE_ID, core_id, 0);
  }
  explicit CmdWaitOdinCoreBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdWaitOdinCore> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdWaitOdinCore>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdWaitOdinCore> CreateCmdWaitOdinCore(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0) {
  CmdWaitOdinCoreBuilder builder_(_fbb);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdWaitOdinCore> CreateCmdWaitOdinCore(::flatbuffers::FlatBufferBuilder &_fbb, const CmdWaitOdinCoreT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdSendPacketT : public ::flatbuffers::NativeTable {
  typedef CmdSendPacket TableType;
  uint8_t core_id = 0;
  std::vector<uint32_t> words{};
};

struct CmdSendPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdSendPacketT NativeTableType;
  typedef CmdSendPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_WORDS = 6
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  const ::flatbuffers::Vector<uint32_t> *words() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_WORDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyOffset(verifier, VT_WORDS) &&
           verifier.VerifyVector(words()) &&
           verifier.EndTable();
  }
  CmdSendPacketT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdSendPacketT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdSendPacket> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSendPacketT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdSendPacketBuilder {
  typedef CmdSendPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdSendPacket::VT_CORE_ID, core_id, 0);
  }
  void add_words(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> words) {
    fbb_.AddOffset(CmdSendPacket::VT_WORDS, words);
  }
  explicit CmdSendPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdSendPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdSendPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdSendPacket> CreateCmdSendPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> words = 0) {
  CmdSendPacketBuilder builder_(_fbb);
  builder_.add_words(words);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CmdSendPacket> CreateCmdSendPacketDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    const std::vector<uint32_t> *words = nullptr) {
  auto words__ = words ? _fbb.CreateVector<uint32_t>(*words) : 0;
  return FB::CreateCmdSendPacket(
      _fbb,
      core_id,
      words__);
}

::flatbuffers::Offset<CmdSendPacket> CreateCmdSendPacket(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSendPacketT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdGetRegmemT : public ::flatbuffers::NativeTable {
  typedef CmdGetRegmem TableType;
  uint8_t core_id = 0;
};

struct CmdGetRegmem FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdGetRegmemT NativeTableType;
  typedef CmdGetRegmemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           verifier.EndTable();
  }
  CmdGetRegmemT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdGetRegmemT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdGetRegmem> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetRegmemT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdGetRegmemBuilder {
  typedef CmdGetRegmem Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdGetRegmem::VT_CORE_ID, core_id, 0);
  }
  explicit CmdGetRegmemBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdGetRegmem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdGetRegmem>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdGetRegmem> CreateCmdGetRegmem(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0) {
  CmdGetRegmemBuilder builder_(_fbb);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdGetRegmem> CreateCmdGetRegmem(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetRegmemT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdSetRegmemT : public ::flatbuffers::NativeTable {
  typedef CmdSetRegmem TableType;
  uint8_t core_id = 0;
  std::unique_ptr<FB::OdinRegmem> regmem{};
  CmdSetRegmemT() = default;
  CmdSetRegmemT(const CmdSetRegmemT &o);
  CmdSetRegmemT(CmdSetRegmemT&&) FLATBUFFERS_NOEXCEPT = default;
  CmdSetRegmemT &operator=(CmdSetRegmemT o) FLATBUFFERS_NOEXCEPT;
};

struct CmdSetRegmem FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdSetRegmemT NativeTableType;
  typedef CmdSetRegmemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_REGMEM = 6
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  const FB::OdinRegmem *regmem() const {
    return GetStruct<const FB::OdinRegmem *>(VT_REGMEM);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyField<FB::OdinRegmem>(verifier, VT_REGMEM, 4) &&
           verifier.EndTable();
  }
  CmdSetRegmemT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdSetRegmemT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdSetRegmem> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetRegmemT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdSetRegmemBuilder {
  typedef CmdSetRegmem Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdSetRegmem::VT_CORE_ID, core_id, 0);
  }
  void add_regmem(const FB::OdinRegmem *regmem) {
    fbb_.AddStruct(CmdSetRegmem::VT_REGMEM, regmem);
  }
  explicit CmdSetRegmemBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdSetRegmem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdSetRegmem>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdSetRegmem> CreateCmdSetRegmem(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    const FB::OdinRegmem *regmem = nullptr) {
  CmdSetRegmemBuilder builder_(_fbb);
  builder_.add_regmem(regmem);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdSetRegmem> CreateCmdSetRegmem(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetRegmemT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdGetNeuronT : public ::flatbuffers::NativeTable {
  typedef CmdGetNeuron TableType;
  uint8_t core_id = 0;
  uint32_t neur_id = 0;
};

struct CmdGetNeuron FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdGetNeuronT NativeTableType;
  typedef CmdGetNeuronBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_NEUR_ID = 6
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  uint32_t neur_id() const {
    return GetField<uint32_t>(VT_NEUR_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyField<uint32_t>(verifier, VT_NEUR_ID, 4) &&
           verifier.EndTable();
  }
  CmdGetNeuronT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdGetNeuronT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdGetNeuron> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetNeuronT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdGetNeuronBuilder {
  typedef CmdGetNeuron Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdGetNeuron::VT_CORE_ID, core_id, 0);
  }
  void add_neur_id(uint32_t neur_id) {
    fbb_.AddElement<uint32_t>(CmdGetNeuron::VT_NEUR_ID, neur_id, 0);
  }
  explicit CmdGetNeuronBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdGetNeuron> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdGetNeuron>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdGetNeuron> CreateCmdGetNeuron(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    uint32_t neur_id = 0) {
  CmdGetNeuronBuilder builder_(_fbb);
  builder_.add_neur_id(neur_id);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdGetNeuron> CreateCmdGetNeuron(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetNeuronT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdSetNeuronT : public ::flatbuffers::NativeTable {
  typedef CmdSetNeuron TableType;
  uint8_t core_id = 0;
  uint32_t neur_id = 0;
  std::unique_ptr<FB::NeuronWords128> neuron_words{};
  CmdSetNeuronT() = default;
  CmdSetNeuronT(const CmdSetNeuronT &o);
  CmdSetNeuronT(CmdSetNeuronT&&) FLATBUFFERS_NOEXCEPT = default;
  CmdSetNeuronT &operator=(CmdSetNeuronT o) FLATBUFFERS_NOEXCEPT;
};

struct CmdSetNeuron FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdSetNeuronT NativeTableType;
  typedef CmdSetNeuronBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_NEUR_ID = 6,
    VT_NEURON_WORDS = 8
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  uint32_t neur_id() const {
    return GetField<uint32_t>(VT_NEUR_ID, 0);
  }
  const FB::NeuronWords128 *neuron_words() const {
    return GetStruct<const FB::NeuronWords128 *>(VT_NEURON_WORDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyField<uint32_t>(verifier, VT_NEUR_ID, 4) &&
           VerifyField<FB::NeuronWords128>(verifier, VT_NEURON_WORDS, 4) &&
           verifier.EndTable();
  }
  CmdSetNeuronT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdSetNeuronT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdSetNeuron> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetNeuronT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdSetNeuronBuilder {
  typedef CmdSetNeuron Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdSetNeuron::VT_CORE_ID, core_id, 0);
  }
  void add_neur_id(uint32_t neur_id) {
    fbb_.AddElement<uint32_t>(CmdSetNeuron::VT_NEUR_ID, neur_id, 0);
  }
  void add_neuron_words(const FB::NeuronWords128 *neuron_words) {
    fbb_.AddStruct(CmdSetNeuron::VT_NEURON_WORDS, neuron_words);
  }
  explicit CmdSetNeuronBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdSetNeuron> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdSetNeuron>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdSetNeuron> CreateCmdSetNeuron(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    uint32_t neur_id = 0,
    const FB::NeuronWords128 *neuron_words = nullptr) {
  CmdSetNeuronBuilder builder_(_fbb);
  builder_.add_neuron_words(neuron_words);
  builder_.add_neur_id(neur_id);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdSetNeuron> CreateCmdSetNeuron(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetNeuronT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdGetSynapseT : public ::flatbuffers::NativeTable {
  typedef CmdGetSynapse TableType;
  uint8_t core_id = 0;
  uint32_t pre_neur_id = 0;
  uint32_t post_neur_id = 0;
};

struct CmdGetSynapse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdGetSynapseT NativeTableType;
  typedef CmdGetSynapseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_PRE_NEUR_ID = 6,
    VT_POST_NEUR_ID = 8
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  uint32_t pre_neur_id() const {
    return GetField<uint32_t>(VT_PRE_NEUR_ID, 0);
  }
  uint32_t post_neur_id() const {
    return GetField<uint32_t>(VT_POST_NEUR_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyField<uint32_t>(verifier, VT_PRE_NEUR_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_POST_NEUR_ID, 4) &&
           verifier.EndTable();
  }
  CmdGetSynapseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdGetSynapseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdGetSynapse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetSynapseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdGetSynapseBuilder {
  typedef CmdGetSynapse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdGetSynapse::VT_CORE_ID, core_id, 0);
  }
  void add_pre_neur_id(uint32_t pre_neur_id) {
    fbb_.AddElement<uint32_t>(CmdGetSynapse::VT_PRE_NEUR_ID, pre_neur_id, 0);
  }
  void add_post_neur_id(uint32_t post_neur_id) {
    fbb_.AddElement<uint32_t>(CmdGetSynapse::VT_POST_NEUR_ID, post_neur_id, 0);
  }
  explicit CmdGetSynapseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdGetSynapse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdGetSynapse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdGetSynapse> CreateCmdGetSynapse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    uint32_t pre_neur_id = 0,
    uint32_t post_neur_id = 0) {
  CmdGetSynapseBuilder builder_(_fbb);
  builder_.add_post_neur_id(post_neur_id);
  builder_.add_pre_neur_id(pre_neur_id);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdGetSynapse> CreateCmdGetSynapse(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetSynapseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdSetSynapseT : public ::flatbuffers::NativeTable {
  typedef CmdSetSynapse TableType;
  uint8_t core_id = 0;
  uint32_t pre_neur_id = 0;
  uint32_t post_neur_id = 0;
  uint8_t weight = 0;
};

struct CmdSetSynapse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdSetSynapseT NativeTableType;
  typedef CmdSetSynapseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_PRE_NEUR_ID = 6,
    VT_POST_NEUR_ID = 8,
    VT_WEIGHT = 10
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  uint32_t pre_neur_id() const {
    return GetField<uint32_t>(VT_PRE_NEUR_ID, 0);
  }
  uint32_t post_neur_id() const {
    return GetField<uint32_t>(VT_POST_NEUR_ID, 0);
  }
  uint8_t weight() const {
    return GetField<uint8_t>(VT_WEIGHT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyField<uint32_t>(verifier, VT_PRE_NEUR_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_POST_NEUR_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_WEIGHT, 1) &&
           verifier.EndTable();
  }
  CmdSetSynapseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdSetSynapseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdSetSynapse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetSynapseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdSetSynapseBuilder {
  typedef CmdSetSynapse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdSetSynapse::VT_CORE_ID, core_id, 0);
  }
  void add_pre_neur_id(uint32_t pre_neur_id) {
    fbb_.AddElement<uint32_t>(CmdSetSynapse::VT_PRE_NEUR_ID, pre_neur_id, 0);
  }
  void add_post_neur_id(uint32_t post_neur_id) {
    fbb_.AddElement<uint32_t>(CmdSetSynapse::VT_POST_NEUR_ID, post_neur_id, 0);
  }
  void add_weight(uint8_t weight) {
    fbb_.AddElement<uint8_t>(CmdSetSynapse::VT_WEIGHT, weight, 0);
  }
  explicit CmdSetSynapseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdSetSynapse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdSetSynapse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdSetSynapse> CreateCmdSetSynapse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    uint32_t pre_neur_id = 0,
    uint32_t post_neur_id = 0,
    uint8_t weight = 0) {
  CmdSetSynapseBuilder builder_(_fbb);
  builder_.add_post_neur_id(post_neur_id);
  builder_.add_pre_neur_id(pre_neur_id);
  builder_.add_weight(weight);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdSetSynapse> CreateCmdSetSynapse(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetSynapseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdResetRouterT : public ::flatbuffers::NativeTable {
  typedef CmdResetRouter TableType;
};

struct CmdResetRouter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdResetRouterT NativeTableType;
  typedef CmdResetRouterBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  CmdResetRouterT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdResetRouterT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdResetRouter> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetRouterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdResetRouterBuilder {
  typedef CmdResetRouter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit CmdResetRouterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdResetRouter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdResetRouter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdResetRouter> CreateCmdResetRouter(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  CmdResetRouterBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdResetRouter> CreateCmdResetRouter(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetRouterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdAddRouteT : public ::flatbuffers::NativeTable {
  typedef CmdAddRoute TableType;
  uint8_t from_core = 0;
  uint8_t from_neur = 0;
  uint8_t to_core = 0;
  uint32_t event_addr = 0;
};

struct CmdAddRoute FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdAddRouteT NativeTableType;
  typedef CmdAddRouteBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FROM_CORE = 4,
    VT_FROM_NEUR = 6,
    VT_TO_CORE = 8,
    VT_EVENT_ADDR = 10
  };
  uint8_t from_core() const {
    return GetField<uint8_t>(VT_FROM_CORE, 0);
  }
  uint8_t from_neur() const {
    return GetField<uint8_t>(VT_FROM_NEUR, 0);
  }
  uint8_t to_core() const {
    return GetField<uint8_t>(VT_TO_CORE, 0);
  }
  uint32_t event_addr() const {
    return GetField<uint32_t>(VT_EVENT_ADDR, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FROM_CORE, 1) &&
           VerifyField<uint8_t>(verifier, VT_FROM_NEUR, 1) &&
           VerifyField<uint8_t>(verifier, VT_TO_CORE, 1) &&
           VerifyField<uint32_t>(verifier, VT_EVENT_ADDR, 4) &&
           verifier.EndTable();
  }
  CmdAddRouteT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdAddRouteT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdAddRoute> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdAddRouteT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdAddRouteBuilder {
  typedef CmdAddRoute Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_from_core(uint8_t from_core) {
    fbb_.AddElement<uint8_t>(CmdAddRoute::VT_FROM_CORE, from_core, 0);
  }
  void add_from_neur(uint8_t from_neur) {
    fbb_.AddElement<uint8_t>(CmdAddRoute::VT_FROM_NEUR, from_neur, 0);
  }
  void add_to_core(uint8_t to_core) {
    fbb_.AddElement<uint8_t>(CmdAddRoute::VT_TO_CORE, to_core, 0);
  }
  void add_event_addr(uint32_t event_addr) {
    fbb_.AddElement<uint32_t>(CmdAddRoute::VT_EVENT_ADDR, event_addr, 0);
  }
  explicit CmdAddRouteBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdAddRoute> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdAddRoute>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdAddRoute> CreateCmdAddRoute(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t from_core = 0,
    uint8_t from_neur = 0,
    uint8_t to_core = 0,
    uint32_t event_addr = 0) {
  CmdAddRouteBuilder builder_(_fbb);
  builder_.add_event_addr(event_addr);
  builder_.add_to_core(to_core);
  builder_.add_from_neur(from_neur);
  builder_.add_from_core(from_core);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdAddRoute> CreateCmdAddRoute(::flatbuffers::FlatBufferBuilder &_fbb, const CmdAddRouteT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdSetServerOutputT : public ::flatbuffers::NativeTable {
  typedef CmdSetServerOutput TableType;
  uint8_t from_core = 0;
  uint8_t from_neur = 0;
  bool server_output = false;
};

struct CmdSetServerOutput FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdSetServerOutputT NativeTableType;
  typedef CmdSetServerOutputBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FROM_CORE = 4,
    VT_FROM_NEUR = 6,
    VT_SERVER_OUTPUT = 8
  };
  uint8_t from_core() const {
    return GetField<uint8_t>(VT_FROM_CORE, 0);
  }
  uint8_t from_neur() const {
    return GetField<uint8_t>(VT_FROM_NEUR, 0);
  }
  bool server_output() const {
    return GetField<uint8_t>(VT_SERVER_OUTPUT, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FROM_CORE, 1) &&
           VerifyField<uint8_t>(verifier, VT_FROM_NEUR, 1) &&
           VerifyField<uint8_t>(verifier, VT_SERVER_OUTPUT, 1) &&
           verifier.EndTable();
  }
  CmdSetServerOutputT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdSetServerOutputT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdSetServerOutput> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetServerOutputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdSetServerOutputBuilder {
  typedef CmdSetServerOutput Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_from_core(uint8_t from_core) {
    fbb_.AddElement<uint8_t>(CmdSetServerOutput::VT_FROM_CORE, from_core, 0);
  }
  void add_from_neur(uint8_t from_neur) {
    fbb_.AddElement<uint8_t>(CmdSetServerOutput::VT_FROM_NEUR, from_neur, 0);
  }
  void add_server_output(bool server_output) {
    fbb_.AddElement<uint8_t>(CmdSetServerOutput::VT_SERVER_OUTPUT, static_cast<uint8_t>(server_output), 0);
  }
  explicit CmdSetServerOutputBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdSetServerOutput> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdSetServerOutput>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdSetServerOutput> CreateCmdSetServerOutput(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t from_core = 0,
    uint8_t from_neur = 0,
    bool server_output = false) {
  CmdSetServerOutputBuilder builder_(_fbb);
  builder_.add_server_output(server_output);
  builder_.add_from_neur(from_neur);
  builder_.add_from_core(from_core);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdSetServerOutput> CreateCmdSetServerOutput(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetServerOutputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdT : public ::flatbuffers::NativeTable {
  typedef Cmd TableType;
  uint32_t handle = 0;
  FB::Cmd_tUnion t{};
};

struct Cmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdT NativeTableType;
  typedef CmdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HANDLE = 4,
    VT_T_TYPE = 6,
    VT_T = 8
  };
  uint32_t handle() const {
    return GetField<uint32_t>(VT_HANDLE, 0);
  }
  FB::Cmd_t t_type() const {
    return static_cast<FB::Cmd_t>(GetField<uint8_t>(VT_T_TYPE, 0));
  }
  const void *t() const {
    return GetPointer<const void *>(VT_T);
  }
  template<typename T> const T *t_as() const;
  const FB::CmdResetAll *t_as_CmdResetAll() const {
    return t_type() == FB::Cmd_t_CmdResetAll ? static_cast<const FB::CmdResetAll *>(t()) : nullptr;
  }
  const FB::CmdResetOdinCore *t_as_CmdResetOdinCore() const {
    return t_type() == FB::Cmd_t_CmdResetOdinCore ? static_cast<const FB::CmdResetOdinCore *>(t()) : nullptr;
  }
  const FB::CmdWaitIdle *t_as_CmdWaitIdle() const {
    return t_type() == FB::Cmd_t_CmdWaitIdle ? static_cast<const FB::CmdWaitIdle *>(t()) : nullptr;
  }
  const FB::CmdWaitOdinCore *t_as_CmdWaitOdinCore() const {
    return t_type() == FB::Cmd_t_CmdWaitOdinCore ? static_cast<const FB::CmdWaitOdinCore *>(t()) : nullptr;
  }
  const FB::CmdSendPacket *t_as_CmdSendPacket() const {
    return t_type() == FB::Cmd_t_CmdSendPacket ? static_cast<const FB::CmdSendPacket *>(t()) : nullptr;
  }
  const FB::CmdGetRegmem *t_as_CmdGetRegmem() const {
    return t_type() == FB::Cmd_t_CmdGetRegmem ? static_cast<const FB::CmdGetRegmem *>(t()) : nullptr;
  }
  const FB::CmdSetRegmem *t_as_CmdSetRegmem() const {
    return t_type() == FB::Cmd_t_CmdSetRegmem ? static_cast<const FB::CmdSetRegmem *>(t()) : nullptr;
  }
  const FB::CmdGetNeuron *t_as_CmdGetNeuron() const {
    return t_type() == FB::Cmd_t_CmdGetNeuron ? static_cast<const FB::CmdGetNeuron *>(t()) : nullptr;
  }
  const FB::CmdSetNeuron *t_as_CmdSetNeuron() const {
    return t_type() == FB::Cmd_t_CmdSetNeuron ? static_cast<const FB::CmdSetNeuron *>(t()) : nullptr;
  }
  const FB::CmdGetSynapse *t_as_CmdGetSynapse() const {
    return t_type() == FB::Cmd_t_CmdGetSynapse ? static_cast<const FB::CmdGetSynapse *>(t()) : nullptr;
  }
  const FB::CmdSetSynapse *t_as_CmdSetSynapse() const {
    return t_type() == FB::Cmd_t_CmdSetSynapse ? static_cast<const FB::CmdSetSynapse *>(t()) : nullptr;
  }
  const FB::CmdResetRouter *t_as_CmdResetRouter() const {
    return t_type() == FB::Cmd_t_CmdResetRouter ? static_cast<const FB::CmdResetRouter *>(t()) : nullptr;
  }
  const FB::CmdAddRoute *t_as_CmdAddRoute() const {
    return t_type() == FB::Cmd_t_CmdAddRoute ? static_cast<const FB::CmdAddRoute *>(t()) : nullptr;
  }
  const FB::CmdSetServerOutput *t_as_CmdSetServerOutput() const {
    return t_type() == FB::Cmd_t_CmdSetServerOutput ? static_cast<const FB::CmdSetServerOutput *>(t()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_HANDLE, 4) &&
           VerifyField<uint8_t>(verifier, VT_T_TYPE, 1) &&
           VerifyOffset(verifier, VT_T) &&
           VerifyCmd_t(verifier, t(), t_type()) &&
           verifier.EndTable();
  }
  CmdT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Cmd> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const FB::CmdResetAll *Cmd::t_as<FB::CmdResetAll>() const {
  return t_as_CmdResetAll();
}

template<> inline const FB::CmdResetOdinCore *Cmd::t_as<FB::CmdResetOdinCore>() const {
  return t_as_CmdResetOdinCore();
}

template<> inline const FB::CmdWaitIdle *Cmd::t_as<FB::CmdWaitIdle>() const {
  return t_as_CmdWaitIdle();
}

template<> inline const FB::CmdWaitOdinCore *Cmd::t_as<FB::CmdWaitOdinCore>() const {
  return t_as_CmdWaitOdinCore();
}

template<> inline const FB::CmdSendPacket *Cmd::t_as<FB::CmdSendPacket>() const {
  return t_as_CmdSendPacket();
}

template<> inline const FB::CmdGetRegmem *Cmd::t_as<FB::CmdGetRegmem>() const {
  return t_as_CmdGetRegmem();
}

template<> inline const FB::CmdSetRegmem *Cmd::t_as<FB::CmdSetRegmem>() const {
  return t_as_CmdSetRegmem();
}

template<> inline const FB::CmdGetNeuron *Cmd::t_as<FB::CmdGetNeuron>() const {
  return t_as_CmdGetNeuron();
}

template<> inline const FB::CmdSetNeuron *Cmd::t_as<FB::CmdSetNeuron>() const {
  return t_as_CmdSetNeuron();
}

template<> inline const FB::CmdGetSynapse *Cmd::t_as<FB::CmdGetSynapse>() const {
  return t_as_CmdGetSynapse();
}

template<> inline const FB::CmdSetSynapse *Cmd::t_as<FB::CmdSetSynapse>() const {
  return t_as_CmdSetSynapse();
}

template<> inline const FB::CmdResetRouter *Cmd::t_as<FB::CmdResetRouter>() const {
  return t_as_CmdResetRouter();
}

template<> inline const FB::CmdAddRoute *Cmd::t_as<FB::CmdAddRoute>() const {
  return t_as_CmdAddRoute();
}

template<> inline const FB::CmdSetServerOutput *Cmd::t_as<FB::CmdSetServerOutput>() const {
  return t_as_CmdSetServerOutput();
}

struct CmdBuilder {
  typedef Cmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_handle(uint32_t handle) {
    fbb_.AddElement<uint32_t>(Cmd::VT_HANDLE, handle, 0);
  }
  void add_t_type(FB::Cmd_t t_type) {
    fbb_.AddElement<uint8_t>(Cmd::VT_T_TYPE, static_cast<uint8_t>(t_type), 0);
  }
  void add_t(::flatbuffers::Offset<void> t) {
    fbb_.AddOffset(Cmd::VT_T, t);
  }
  explicit CmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Cmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Cmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Cmd> CreateCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t handle = 0,
    FB::Cmd_t t_type = FB::Cmd_t_NONE,
    ::flatbuffers::Offset<void> t = 0) {
  CmdBuilder builder_(_fbb);
  builder_.add_t(t);
  builder_.add_handle(handle);
  builder_.add_t_type(t_type);
  return builder_.Finish();
}

::flatbuffers::Offset<Cmd> CreateCmd(::flatbuffers::FlatBufferBuilder &_fbb, const CmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CmdResetAllT *CmdResetAll::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdResetAllT>(new CmdResetAllT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdResetAll::UnPackTo(CmdResetAllT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<CmdResetAll> CreateCmdResetAll(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetAllT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdResetAll::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdResetAll> CmdResetAll::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetAllT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdResetAllT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return FB::CreateCmdResetAll(
      _fbb);
}

inline CmdResetOdinCoreT *CmdResetOdinCore::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdResetOdinCoreT>(new CmdResetOdinCoreT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdResetOdinCore::UnPackTo(CmdResetOdinCoreT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
}

inline ::flatbuffers::Offset<CmdResetOdinCore> CreateCmdResetOdinCore(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetOdinCoreT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdResetOdinCore::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdResetOdinCore> CmdResetOdinCore::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetOdinCoreT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdResetOdinCoreT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  return FB::CreateCmdResetOdinCore(
      _fbb,
      _core_id);
}

inline CmdWaitIdleT *CmdWaitIdle::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdWaitIdleT>(new CmdWaitIdleT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdWaitIdle::UnPackTo(CmdWaitIdleT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<CmdWaitIdle> CreateCmdWaitIdle(::flatbuffers::FlatBufferBuilder &_fbb, const CmdWaitIdleT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdWaitIdle::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdWaitIdle> CmdWaitIdle::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdWaitIdleT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdWaitIdleT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return FB::CreateCmdWaitIdle(
      _fbb);
}

inline CmdWaitOdinCoreT *CmdWaitOdinCore::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdWaitOdinCoreT>(new CmdWaitOdinCoreT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdWaitOdinCore::UnPackTo(CmdWaitOdinCoreT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
}

inline ::flatbuffers::Offset<CmdWaitOdinCore> CreateCmdWaitOdinCore(::flatbuffers::FlatBufferBuilder &_fbb, const CmdWaitOdinCoreT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdWaitOdinCore::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdWaitOdinCore> CmdWaitOdinCore::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdWaitOdinCoreT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdWaitOdinCoreT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  return FB::CreateCmdWaitOdinCore(
      _fbb,
      _core_id);
}

inline CmdSendPacketT *CmdSendPacket::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdSendPacketT>(new CmdSendPacketT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdSendPacket::UnPackTo(CmdSendPacketT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = words(); if (_e) { _o->words.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->words[_i] = _e->Get(_i); } } else { _o->words.resize(0); } }
}

inline ::flatbuffers::Offset<CmdSendPacket> CreateCmdSendPacket(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSendPacketT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdSendPacket::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdSendPacket> CmdSendPacket::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSendPacketT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdSendPacketT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _words = _o->words.size() ? _fbb.CreateVector(_o->words) : 0;
  return FB::CreateCmdSendPacket(
      _fbb,
      _core_id,
      _words);
}

inline CmdGetRegmemT *CmdGetRegmem::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdGetRegmemT>(new CmdGetRegmemT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdGetRegmem::UnPackTo(CmdGetRegmemT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
}

inline ::flatbuffers::Offset<CmdGetRegmem> CreateCmdGetRegmem(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetRegmemT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdGetRegmem::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdGetRegmem> CmdGetRegmem::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetRegmemT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdGetRegmemT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  return FB::CreateCmdGetRegmem(
      _fbb,
      _core_id);
}

inline CmdSetRegmemT::CmdSetRegmemT(const CmdSetRegmemT &o)
      : core_id(o.core_id),
        regmem((o.regmem) ? new FB::OdinRegmem(*o.regmem) : nullptr) {
}

inline CmdSetRegmemT &CmdSetRegmemT::operator=(CmdSetRegmemT o) FLATBUFFERS_NOEXCEPT {
  std::swap(core_id, o.core_id);
  std::swap(regmem, o.regmem);
  return *this;
}

inline CmdSetRegmemT *CmdSetRegmem::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdSetRegmemT>(new CmdSetRegmemT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdSetRegmem::UnPackTo(CmdSetRegmemT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = regmem(); if (_e) _o->regmem = std::unique_ptr<FB::OdinRegmem>(new FB::OdinRegmem(*_e)); }
}

inline ::flatbuffers::Offset<CmdSetRegmem> CreateCmdSetRegmem(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetRegmemT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdSetRegmem::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdSetRegmem> CmdSetRegmem::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetRegmemT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdSetRegmemT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _regmem = _o->regmem ? _o->regmem.get() : nullptr;
  return FB::CreateCmdSetRegmem(
      _fbb,
      _core_id,
      _regmem);
}

inline CmdGetNeuronT *CmdGetNeuron::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdGetNeuronT>(new CmdGetNeuronT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdGetNeuron::UnPackTo(CmdGetNeuronT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = neur_id(); _o->neur_id = _e; }
}

inline ::flatbuffers::Offset<CmdGetNeuron> CreateCmdGetNeuron(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetNeuronT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdGetNeuron::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdGetNeuron> CmdGetNeuron::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetNeuronT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdGetNeuronT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _neur_id = _o->neur_id;
  return FB::CreateCmdGetNeuron(
      _fbb,
      _core_id,
      _neur_id);
}

inline CmdSetNeuronT::CmdSetNeuronT(const CmdSetNeuronT &o)
      : core_id(o.core_id),
        neur_id(o.neur_id),
        neuron_words((o.neuron_words) ? new FB::NeuronWords128(*o.neuron_words) : nullptr) {
}

inline CmdSetNeuronT &CmdSetNeuronT::operator=(CmdSetNeuronT o) FLATBUFFERS_NOEXCEPT {
  std::swap(core_id, o.core_id);
  std::swap(neur_id, o.neur_id);
  std::swap(neuron_words, o.neuron_words);
  return *this;
}

inline CmdSetNeuronT *CmdSetNeuron::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdSetNeuronT>(new CmdSetNeuronT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdSetNeuron::UnPackTo(CmdSetNeuronT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = neur_id(); _o->neur_id = _e; }
  { auto _e = neuron_words(); if (_e) _o->neuron_words = std::unique_ptr<FB::NeuronWords128>(new FB::NeuronWords128(*_e)); }
}

inline ::flatbuffers::Offset<CmdSetNeuron> CreateCmdSetNeuron(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetNeuronT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdSetNeuron::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdSetNeuron> CmdSetNeuron::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetNeuronT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdSetNeuronT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _neur_id = _o->neur_id;
  auto _neuron_words = _o->neuron_words ? _o->neuron_words.get() : nullptr;
  return FB::CreateCmdSetNeuron(
      _fbb,
      _core_id,
      _neur_id,
      _neuron_words);
}

inline CmdGetSynapseT *CmdGetSynapse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdGetSynapseT>(new CmdGetSynapseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdGetSynapse::UnPackTo(CmdGetSynapseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = pre_neur_id(); _o->pre_neur_id = _e; }
  { auto _e = post_neur_id(); _o->post_neur_id = _e; }
}

inline ::flatbuffers::Offset<CmdGetSynapse> CreateCmdGetSynapse(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetSynapseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdGetSynapse::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdGetSynapse> CmdGetSynapse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdGetSynapseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdGetSynapseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _pre_neur_id = _o->pre_neur_id;
  auto _post_neur_id = _o->post_neur_id;
  return FB::CreateCmdGetSynapse(
      _fbb,
      _core_id,
      _pre_neur_id,
      _post_neur_id);
}

inline CmdSetSynapseT *CmdSetSynapse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdSetSynapseT>(new CmdSetSynapseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdSetSynapse::UnPackTo(CmdSetSynapseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = pre_neur_id(); _o->pre_neur_id = _e; }
  { auto _e = post_neur_id(); _o->post_neur_id = _e; }
  { auto _e = weight(); _o->weight = _e; }
}

inline ::flatbuffers::Offset<CmdSetSynapse> CreateCmdSetSynapse(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetSynapseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdSetSynapse::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdSetSynapse> CmdSetSynapse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetSynapseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdSetSynapseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _pre_neur_id = _o->pre_neur_id;
  auto _post_neur_id = _o->post_neur_id;
  auto _weight = _o->weight;
  return FB::CreateCmdSetSynapse(
      _fbb,
      _core_id,
      _pre_neur_id,
      _post_neur_id,
      _weight);
}

inline CmdResetRouterT *CmdResetRouter::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdResetRouterT>(new CmdResetRouterT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdResetRouter::UnPackTo(CmdResetRouterT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<CmdResetRouter> CreateCmdResetRouter(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetRouterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdResetRouter::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdResetRouter> CmdResetRouter::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdResetRouterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdResetRouterT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return FB::CreateCmdResetRouter(
      _fbb);
}

inline CmdAddRouteT *CmdAddRoute::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdAddRouteT>(new CmdAddRouteT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdAddRoute::UnPackTo(CmdAddRouteT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = from_core(); _o->from_core = _e; }
  { auto _e = from_neur(); _o->from_neur = _e; }
  { auto _e = to_core(); _o->to_core = _e; }
  { auto _e = event_addr(); _o->event_addr = _e; }
}

inline ::flatbuffers::Offset<CmdAddRoute> CreateCmdAddRoute(::flatbuffers::FlatBufferBuilder &_fbb, const CmdAddRouteT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdAddRoute::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdAddRoute> CmdAddRoute::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdAddRouteT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdAddRouteT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _from_core = _o->from_core;
  auto _from_neur = _o->from_neur;
  auto _to_core = _o->to_core;
  auto _event_addr = _o->event_addr;
  return FB::CreateCmdAddRoute(
      _fbb,
      _from_core,
      _from_neur,
      _to_core,
      _event_addr);
}

inline CmdSetServerOutputT *CmdSetServerOutput::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdSetServerOutputT>(new CmdSetServerOutputT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdSetServerOutput::UnPackTo(CmdSetServerOutputT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = from_core(); _o->from_core = _e; }
  { auto _e = from_neur(); _o->from_neur = _e; }
  { auto _e = server_output(); _o->server_output = _e; }
}

inline ::flatbuffers::Offset<CmdSetServerOutput> CreateCmdSetServerOutput(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetServerOutputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdSetServerOutput::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdSetServerOutput> CmdSetServerOutput::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdSetServerOutputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdSetServerOutputT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _from_core = _o->from_core;
  auto _from_neur = _o->from_neur;
  auto _server_output = _o->server_output;
  return FB::CreateCmdSetServerOutput(
      _fbb,
      _from_core,
      _from_neur,
      _server_output);
}

inline CmdT *Cmd::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdT>(new CmdT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Cmd::UnPackTo(CmdT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = handle(); _o->handle = _e; }
  { auto _e = t_type(); _o->t.type = _e; }
  { auto _e = t(); if (_e) _o->t.value = FB::Cmd_tUnion::UnPack(_e, t_type(), _resolver); }
}

inline ::flatbuffers::Offset<Cmd> CreateCmd(::flatbuffers::FlatBufferBuilder &_fbb, const CmdT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Cmd::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Cmd> Cmd::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _handle = _o->handle;
  auto _t_type = _o->t.type;
  auto _t = _o->t.Pack(_fbb);
  return FB::CreateCmd(
      _fbb,
      _handle,
      _t_type,
      _t);
}

template <bool B>
inline bool VerifyCmd_t(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Cmd_t type) {
  switch (type) {
    case Cmd_t_NONE: {
      return true;
    }
    case Cmd_t_CmdResetAll: {
      auto ptr = reinterpret_cast<const FB::CmdResetAll *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdResetOdinCore: {
      auto ptr = reinterpret_cast<const FB::CmdResetOdinCore *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdWaitIdle: {
      auto ptr = reinterpret_cast<const FB::CmdWaitIdle *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdWaitOdinCore: {
      auto ptr = reinterpret_cast<const FB::CmdWaitOdinCore *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdSendPacket: {
      auto ptr = reinterpret_cast<const FB::CmdSendPacket *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdGetRegmem: {
      auto ptr = reinterpret_cast<const FB::CmdGetRegmem *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdSetRegmem: {
      auto ptr = reinterpret_cast<const FB::CmdSetRegmem *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdGetNeuron: {
      auto ptr = reinterpret_cast<const FB::CmdGetNeuron *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdSetNeuron: {
      auto ptr = reinterpret_cast<const FB::CmdSetNeuron *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdGetSynapse: {
      auto ptr = reinterpret_cast<const FB::CmdGetSynapse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdSetSynapse: {
      auto ptr = reinterpret_cast<const FB::CmdSetSynapse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdResetRouter: {
      auto ptr = reinterpret_cast<const FB::CmdResetRouter *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdAddRoute: {
      auto ptr = reinterpret_cast<const FB::CmdAddRoute *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd_t_CmdSetServerOutput: {
      auto ptr = reinterpret_cast<const FB::CmdSetServerOutput *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyCmd_tVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCmd_t(
        verifier,  values->Get(i), types->GetEnum<Cmd_t>(i))) {
      return false;
    }
  }
  return true;
}

inline void *Cmd_tUnion::UnPack(const void *obj, Cmd_t type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case Cmd_t_CmdResetAll: {
      auto ptr = reinterpret_cast<const FB::CmdResetAll *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdResetOdinCore: {
      auto ptr = reinterpret_cast<const FB::CmdResetOdinCore *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdWaitIdle: {
      auto ptr = reinterpret_cast<const FB::CmdWaitIdle *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdWaitOdinCore: {
      auto ptr = reinterpret_cast<const FB::CmdWaitOdinCore *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdSendPacket: {
      auto ptr = reinterpret_cast<const FB::CmdSendPacket *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdGetRegmem: {
      auto ptr = reinterpret_cast<const FB::CmdGetRegmem *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdSetRegmem: {
      auto ptr = reinterpret_cast<const FB::CmdSetRegmem *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdGetNeuron: {
      auto ptr = reinterpret_cast<const FB::CmdGetNeuron *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdSetNeuron: {
      auto ptr = reinterpret_cast<const FB::CmdSetNeuron *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdGetSynapse: {
      auto ptr = reinterpret_cast<const FB::CmdGetSynapse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdSetSynapse: {
      auto ptr = reinterpret_cast<const FB::CmdSetSynapse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdResetRouter: {
      auto ptr = reinterpret_cast<const FB::CmdResetRouter *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdAddRoute: {
      auto ptr = reinterpret_cast<const FB::CmdAddRoute *>(obj);
      return ptr->UnPack(resolver);
    }
    case Cmd_t_CmdSetServerOutput: {
      auto ptr = reinterpret_cast<const FB::CmdSetServerOutput *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> Cmd_tUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case Cmd_t_CmdResetAll: {
      auto ptr = reinterpret_cast<const FB::CmdResetAllT *>(value);
      return CreateCmdResetAll(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdResetOdinCore: {
      auto ptr = reinterpret_cast<const FB::CmdResetOdinCoreT *>(value);
      return CreateCmdResetOdinCore(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdWaitIdle: {
      auto ptr = reinterpret_cast<const FB::CmdWaitIdleT *>(value);
      return CreateCmdWaitIdle(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdWaitOdinCore: {
      auto ptr = reinterpret_cast<const FB::CmdWaitOdinCoreT *>(value);
      return CreateCmdWaitOdinCore(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdSendPacket: {
      auto ptr = reinterpret_cast<const FB::CmdSendPacketT *>(value);
      return CreateCmdSendPacket(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdGetRegmem: {
      auto ptr = reinterpret_cast<const FB::CmdGetRegmemT *>(value);
      return CreateCmdGetRegmem(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdSetRegmem: {
      auto ptr = reinterpret_cast<const FB::CmdSetRegmemT *>(value);
      return CreateCmdSetRegmem(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdGetNeuron: {
      auto ptr = reinterpret_cast<const FB::CmdGetNeuronT *>(value);
      return CreateCmdGetNeuron(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdSetNeuron: {
      auto ptr = reinterpret_cast<const FB::CmdSetNeuronT *>(value);
      return CreateCmdSetNeuron(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdGetSynapse: {
      auto ptr = reinterpret_cast<const FB::CmdGetSynapseT *>(value);
      return CreateCmdGetSynapse(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdSetSynapse: {
      auto ptr = reinterpret_cast<const FB::CmdSetSynapseT *>(value);
      return CreateCmdSetSynapse(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdResetRouter: {
      auto ptr = reinterpret_cast<const FB::CmdResetRouterT *>(value);
      return CreateCmdResetRouter(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdAddRoute: {
      auto ptr = reinterpret_cast<const FB::CmdAddRouteT *>(value);
      return CreateCmdAddRoute(_fbb, ptr, _rehasher).Union();
    }
    case Cmd_t_CmdSetServerOutput: {
      auto ptr = reinterpret_cast<const FB::CmdSetServerOutputT *>(value);
      return CreateCmdSetServerOutput(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline Cmd_tUnion::Cmd_tUnion(const Cmd_tUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Cmd_t_CmdResetAll: {
      value = new FB::CmdResetAllT(*reinterpret_cast<FB::CmdResetAllT *>(u.value));
      break;
    }
    case Cmd_t_CmdResetOdinCore: {
      value = new FB::CmdResetOdinCoreT(*reinterpret_cast<FB::CmdResetOdinCoreT *>(u.value));
      break;
    }
    case Cmd_t_CmdWaitIdle: {
      value = new FB::CmdWaitIdleT(*reinterpret_cast<FB::CmdWaitIdleT *>(u.value));
      break;
    }
    case Cmd_t_CmdWaitOdinCore: {
      value = new FB::CmdWaitOdinCoreT(*reinterpret_cast<FB::CmdWaitOdinCoreT *>(u.value));
      break;
    }
    case Cmd_t_CmdSendPacket: {
      value = new FB::CmdSendPacketT(*reinterpret_cast<FB::CmdSendPacketT *>(u.value));
      break;
    }
    case Cmd_t_CmdGetRegmem: {
      value = new FB::CmdGetRegmemT(*reinterpret_cast<FB::CmdGetRegmemT *>(u.value));
      break;
    }
    case Cmd_t_CmdSetRegmem: {
      value = new FB::CmdSetRegmemT(*reinterpret_cast<FB::CmdSetRegmemT *>(u.value));
      break;
    }
    case Cmd_t_CmdGetNeuron: {
      value = new FB::CmdGetNeuronT(*reinterpret_cast<FB::CmdGetNeuronT *>(u.value));
      break;
    }
    case Cmd_t_CmdSetNeuron: {
      value = new FB::CmdSetNeuronT(*reinterpret_cast<FB::CmdSetNeuronT *>(u.value));
      break;
    }
    case Cmd_t_CmdGetSynapse: {
      value = new FB::CmdGetSynapseT(*reinterpret_cast<FB::CmdGetSynapseT *>(u.value));
      break;
    }
    case Cmd_t_CmdSetSynapse: {
      value = new FB::CmdSetSynapseT(*reinterpret_cast<FB::CmdSetSynapseT *>(u.value));
      break;
    }
    case Cmd_t_CmdResetRouter: {
      value = new FB::CmdResetRouterT(*reinterpret_cast<FB::CmdResetRouterT *>(u.value));
      break;
    }
    case Cmd_t_CmdAddRoute: {
      value = new FB::CmdAddRouteT(*reinterpret_cast<FB::CmdAddRouteT *>(u.value));
      break;
    }
    case Cmd_t_CmdSetServerOutput: {
      value = new FB::CmdSetServerOutputT(*reinterpret_cast<FB::CmdSetServerOutputT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void Cmd_tUnion::Reset() {
  switch (type) {
    case Cmd_t_CmdResetAll: {
      auto ptr = reinterpret_cast<FB::CmdResetAllT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdResetOdinCore: {
      auto ptr = reinterpret_cast<FB::CmdResetOdinCoreT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdWaitIdle: {
      auto ptr = reinterpret_cast<FB::CmdWaitIdleT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdWaitOdinCore: {
      auto ptr = reinterpret_cast<FB::CmdWaitOdinCoreT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdSendPacket: {
      auto ptr = reinterpret_cast<FB::CmdSendPacketT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdGetRegmem: {
      auto ptr = reinterpret_cast<FB::CmdGetRegmemT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdSetRegmem: {
      auto ptr = reinterpret_cast<FB::CmdSetRegmemT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdGetNeuron: {
      auto ptr = reinterpret_cast<FB::CmdGetNeuronT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdSetNeuron: {
      auto ptr = reinterpret_cast<FB::CmdSetNeuronT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdGetSynapse: {
      auto ptr = reinterpret_cast<FB::CmdGetSynapseT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdSetSynapse: {
      auto ptr = reinterpret_cast<FB::CmdSetSynapseT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdResetRouter: {
      auto ptr = reinterpret_cast<FB::CmdResetRouterT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdAddRoute: {
      auto ptr = reinterpret_cast<FB::CmdAddRouteT *>(value);
      delete ptr;
      break;
    }
    case Cmd_t_CmdSetServerOutput: {
      auto ptr = reinterpret_cast<FB::CmdSetServerOutputT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Cmd_t_NONE;
}

}  // namespace FB

#endif  // FLATBUFFERS_GENERATED_CMD_FB_H_
