// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CMDOUTPUT_FB_H_
#define FLATBUFFERS_GENERATED_CMDOUTPUT_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "cmd_generated.h"
#include "odin_types_generated.h"

namespace FB {

struct CmdOutputNone;
struct CmdOutputNoneBuilder;
struct CmdOutputNoneT;

struct CmdOutputGetRegmem;
struct CmdOutputGetRegmemBuilder;
struct CmdOutputGetRegmemT;

struct CmdOutputGetNeuron;
struct CmdOutputGetNeuronBuilder;
struct CmdOutputGetNeuronT;

struct CmdOutputGetSynapse;
struct CmdOutputGetSynapseBuilder;
struct CmdOutputGetSynapseT;

struct CmdOutput;
struct CmdOutputBuilder;
struct CmdOutputT;

enum CmdOutput_t : uint8_t {
  CmdOutput_t_NONE = 0,
  CmdOutput_t_CmdOutputNone = 1,
  CmdOutput_t_CmdOutputGetRegmem = 2,
  CmdOutput_t_CmdOutputGetNeuron = 3,
  CmdOutput_t_CmdOutputGetSynapse = 4,
  CmdOutput_t_MIN = CmdOutput_t_NONE,
  CmdOutput_t_MAX = CmdOutput_t_CmdOutputGetSynapse
};

inline const CmdOutput_t (&EnumValuesCmdOutput_t())[5] {
  static const CmdOutput_t values[] = {
    CmdOutput_t_NONE,
    CmdOutput_t_CmdOutputNone,
    CmdOutput_t_CmdOutputGetRegmem,
    CmdOutput_t_CmdOutputGetNeuron,
    CmdOutput_t_CmdOutputGetSynapse
  };
  return values;
}

inline const char * const *EnumNamesCmdOutput_t() {
  static const char * const names[6] = {
    "NONE",
    "CmdOutputNone",
    "CmdOutputGetRegmem",
    "CmdOutputGetNeuron",
    "CmdOutputGetSynapse",
    nullptr
  };
  return names;
}

inline const char *EnumNameCmdOutput_t(CmdOutput_t e) {
  if (::flatbuffers::IsOutRange(e, CmdOutput_t_NONE, CmdOutput_t_CmdOutputGetSynapse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCmdOutput_t()[index];
}

template<typename T> struct CmdOutput_tTraits {
  static const CmdOutput_t enum_value = CmdOutput_t_NONE;
};

template<> struct CmdOutput_tTraits<FB::CmdOutputNone> {
  static const CmdOutput_t enum_value = CmdOutput_t_CmdOutputNone;
};

template<> struct CmdOutput_tTraits<FB::CmdOutputGetRegmem> {
  static const CmdOutput_t enum_value = CmdOutput_t_CmdOutputGetRegmem;
};

template<> struct CmdOutput_tTraits<FB::CmdOutputGetNeuron> {
  static const CmdOutput_t enum_value = CmdOutput_t_CmdOutputGetNeuron;
};

template<> struct CmdOutput_tTraits<FB::CmdOutputGetSynapse> {
  static const CmdOutput_t enum_value = CmdOutput_t_CmdOutputGetSynapse;
};

template<typename T> struct CmdOutput_tUnionTraits {
  static const CmdOutput_t enum_value = CmdOutput_t_NONE;
};

template<> struct CmdOutput_tUnionTraits<FB::CmdOutputNoneT> {
  static const CmdOutput_t enum_value = CmdOutput_t_CmdOutputNone;
};

template<> struct CmdOutput_tUnionTraits<FB::CmdOutputGetRegmemT> {
  static const CmdOutput_t enum_value = CmdOutput_t_CmdOutputGetRegmem;
};

template<> struct CmdOutput_tUnionTraits<FB::CmdOutputGetNeuronT> {
  static const CmdOutput_t enum_value = CmdOutput_t_CmdOutputGetNeuron;
};

template<> struct CmdOutput_tUnionTraits<FB::CmdOutputGetSynapseT> {
  static const CmdOutput_t enum_value = CmdOutput_t_CmdOutputGetSynapse;
};

struct CmdOutput_tUnion {
  CmdOutput_t type;
  void *value;

  CmdOutput_tUnion() : type(CmdOutput_t_NONE), value(nullptr) {}
  CmdOutput_tUnion(CmdOutput_tUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(CmdOutput_t_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  CmdOutput_tUnion(const CmdOutput_tUnion &);
  CmdOutput_tUnion &operator=(const CmdOutput_tUnion &u)
    { CmdOutput_tUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  CmdOutput_tUnion &operator=(CmdOutput_tUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~CmdOutput_tUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = CmdOutput_tUnionTraits<RT>::enum_value;
    if (type != CmdOutput_t_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, CmdOutput_t type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  FB::CmdOutputNoneT *AsCmdOutputNone() {
    return type == CmdOutput_t_CmdOutputNone ?
      reinterpret_cast<FB::CmdOutputNoneT *>(value) : nullptr;
  }
  const FB::CmdOutputNoneT *AsCmdOutputNone() const {
    return type == CmdOutput_t_CmdOutputNone ?
      reinterpret_cast<const FB::CmdOutputNoneT *>(value) : nullptr;
  }
  FB::CmdOutputGetRegmemT *AsCmdOutputGetRegmem() {
    return type == CmdOutput_t_CmdOutputGetRegmem ?
      reinterpret_cast<FB::CmdOutputGetRegmemT *>(value) : nullptr;
  }
  const FB::CmdOutputGetRegmemT *AsCmdOutputGetRegmem() const {
    return type == CmdOutput_t_CmdOutputGetRegmem ?
      reinterpret_cast<const FB::CmdOutputGetRegmemT *>(value) : nullptr;
  }
  FB::CmdOutputGetNeuronT *AsCmdOutputGetNeuron() {
    return type == CmdOutput_t_CmdOutputGetNeuron ?
      reinterpret_cast<FB::CmdOutputGetNeuronT *>(value) : nullptr;
  }
  const FB::CmdOutputGetNeuronT *AsCmdOutputGetNeuron() const {
    return type == CmdOutput_t_CmdOutputGetNeuron ?
      reinterpret_cast<const FB::CmdOutputGetNeuronT *>(value) : nullptr;
  }
  FB::CmdOutputGetSynapseT *AsCmdOutputGetSynapse() {
    return type == CmdOutput_t_CmdOutputGetSynapse ?
      reinterpret_cast<FB::CmdOutputGetSynapseT *>(value) : nullptr;
  }
  const FB::CmdOutputGetSynapseT *AsCmdOutputGetSynapse() const {
    return type == CmdOutput_t_CmdOutputGetSynapse ?
      reinterpret_cast<const FB::CmdOutputGetSynapseT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyCmdOutput_t(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, CmdOutput_t type);
template <bool B = false>
bool VerifyCmdOutput_tVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct CmdOutputNoneT : public ::flatbuffers::NativeTable {
  typedef CmdOutputNone TableType;
};

struct CmdOutputNone FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdOutputNoneT NativeTableType;
  typedef CmdOutputNoneBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  CmdOutputNoneT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdOutputNoneT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdOutputNone> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputNoneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdOutputNoneBuilder {
  typedef CmdOutputNone Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit CmdOutputNoneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdOutputNone> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdOutputNone>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdOutputNone> CreateCmdOutputNone(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  CmdOutputNoneBuilder builder_(_fbb);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdOutputNone> CreateCmdOutputNone(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputNoneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdOutputGetRegmemT : public ::flatbuffers::NativeTable {
  typedef CmdOutputGetRegmem TableType;
  uint8_t core_id = 0;
  std::unique_ptr<FB::OdinRegmem> regmem{};
  CmdOutputGetRegmemT() = default;
  CmdOutputGetRegmemT(const CmdOutputGetRegmemT &o);
  CmdOutputGetRegmemT(CmdOutputGetRegmemT&&) FLATBUFFERS_NOEXCEPT = default;
  CmdOutputGetRegmemT &operator=(CmdOutputGetRegmemT o) FLATBUFFERS_NOEXCEPT;
};

struct CmdOutputGetRegmem FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdOutputGetRegmemT NativeTableType;
  typedef CmdOutputGetRegmemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_REGMEM = 6
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  const FB::OdinRegmem *regmem() const {
    return GetStruct<const FB::OdinRegmem *>(VT_REGMEM);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyField<FB::OdinRegmem>(verifier, VT_REGMEM, 4) &&
           verifier.EndTable();
  }
  CmdOutputGetRegmemT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdOutputGetRegmemT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdOutputGetRegmem> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetRegmemT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdOutputGetRegmemBuilder {
  typedef CmdOutputGetRegmem Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdOutputGetRegmem::VT_CORE_ID, core_id, 0);
  }
  void add_regmem(const FB::OdinRegmem *regmem) {
    fbb_.AddStruct(CmdOutputGetRegmem::VT_REGMEM, regmem);
  }
  explicit CmdOutputGetRegmemBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdOutputGetRegmem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdOutputGetRegmem>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdOutputGetRegmem> CreateCmdOutputGetRegmem(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    const FB::OdinRegmem *regmem = nullptr) {
  CmdOutputGetRegmemBuilder builder_(_fbb);
  builder_.add_regmem(regmem);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdOutputGetRegmem> CreateCmdOutputGetRegmem(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetRegmemT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdOutputGetNeuronT : public ::flatbuffers::NativeTable {
  typedef CmdOutputGetNeuron TableType;
  uint8_t core_id = 0;
  uint32_t neur_id = 0;
  std::unique_ptr<FB::NeuronWords128> neuron_words{};
  CmdOutputGetNeuronT() = default;
  CmdOutputGetNeuronT(const CmdOutputGetNeuronT &o);
  CmdOutputGetNeuronT(CmdOutputGetNeuronT&&) FLATBUFFERS_NOEXCEPT = default;
  CmdOutputGetNeuronT &operator=(CmdOutputGetNeuronT o) FLATBUFFERS_NOEXCEPT;
};

struct CmdOutputGetNeuron FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdOutputGetNeuronT NativeTableType;
  typedef CmdOutputGetNeuronBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_NEUR_ID = 6,
    VT_NEURON_WORDS = 8
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  uint32_t neur_id() const {
    return GetField<uint32_t>(VT_NEUR_ID, 0);
  }
  const FB::NeuronWords128 *neuron_words() const {
    return GetStruct<const FB::NeuronWords128 *>(VT_NEURON_WORDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyField<uint32_t>(verifier, VT_NEUR_ID, 4) &&
           VerifyField<FB::NeuronWords128>(verifier, VT_NEURON_WORDS, 4) &&
           verifier.EndTable();
  }
  CmdOutputGetNeuronT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdOutputGetNeuronT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdOutputGetNeuron> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetNeuronT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdOutputGetNeuronBuilder {
  typedef CmdOutputGetNeuron Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdOutputGetNeuron::VT_CORE_ID, core_id, 0);
  }
  void add_neur_id(uint32_t neur_id) {
    fbb_.AddElement<uint32_t>(CmdOutputGetNeuron::VT_NEUR_ID, neur_id, 0);
  }
  void add_neuron_words(const FB::NeuronWords128 *neuron_words) {
    fbb_.AddStruct(CmdOutputGetNeuron::VT_NEURON_WORDS, neuron_words);
  }
  explicit CmdOutputGetNeuronBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdOutputGetNeuron> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdOutputGetNeuron>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdOutputGetNeuron> CreateCmdOutputGetNeuron(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    uint32_t neur_id = 0,
    const FB::NeuronWords128 *neuron_words = nullptr) {
  CmdOutputGetNeuronBuilder builder_(_fbb);
  builder_.add_neuron_words(neuron_words);
  builder_.add_neur_id(neur_id);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdOutputGetNeuron> CreateCmdOutputGetNeuron(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetNeuronT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdOutputGetSynapseT : public ::flatbuffers::NativeTable {
  typedef CmdOutputGetSynapse TableType;
  uint8_t core_id = 0;
  uint32_t pre_neur_id = 0;
  uint32_t post_neur_id = 0;
  uint8_t weight = 0;
};

struct CmdOutputGetSynapse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdOutputGetSynapseT NativeTableType;
  typedef CmdOutputGetSynapseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_PRE_NEUR_ID = 6,
    VT_POST_NEUR_ID = 8,
    VT_WEIGHT = 10
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  uint32_t pre_neur_id() const {
    return GetField<uint32_t>(VT_PRE_NEUR_ID, 0);
  }
  uint32_t post_neur_id() const {
    return GetField<uint32_t>(VT_POST_NEUR_ID, 0);
  }
  uint8_t weight() const {
    return GetField<uint8_t>(VT_WEIGHT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyField<uint32_t>(verifier, VT_PRE_NEUR_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_POST_NEUR_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_WEIGHT, 1) &&
           verifier.EndTable();
  }
  CmdOutputGetSynapseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdOutputGetSynapseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdOutputGetSynapse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetSynapseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CmdOutputGetSynapseBuilder {
  typedef CmdOutputGetSynapse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(CmdOutputGetSynapse::VT_CORE_ID, core_id, 0);
  }
  void add_pre_neur_id(uint32_t pre_neur_id) {
    fbb_.AddElement<uint32_t>(CmdOutputGetSynapse::VT_PRE_NEUR_ID, pre_neur_id, 0);
  }
  void add_post_neur_id(uint32_t post_neur_id) {
    fbb_.AddElement<uint32_t>(CmdOutputGetSynapse::VT_POST_NEUR_ID, post_neur_id, 0);
  }
  void add_weight(uint8_t weight) {
    fbb_.AddElement<uint8_t>(CmdOutputGetSynapse::VT_WEIGHT, weight, 0);
  }
  explicit CmdOutputGetSynapseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdOutputGetSynapse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdOutputGetSynapse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdOutputGetSynapse> CreateCmdOutputGetSynapse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    uint32_t pre_neur_id = 0,
    uint32_t post_neur_id = 0,
    uint8_t weight = 0) {
  CmdOutputGetSynapseBuilder builder_(_fbb);
  builder_.add_post_neur_id(post_neur_id);
  builder_.add_pre_neur_id(pre_neur_id);
  builder_.add_weight(weight);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdOutputGetSynapse> CreateCmdOutputGetSynapse(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetSynapseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CmdOutputT : public ::flatbuffers::NativeTable {
  typedef CmdOutput TableType;
  uint32_t handle = 0;
  FB::CmdOutput_tUnion t{};
};

struct CmdOutput FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdOutputT NativeTableType;
  typedef CmdOutputBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HANDLE = 4,
    VT_T_TYPE = 6,
    VT_T = 8
  };
  uint32_t handle() const {
    return GetField<uint32_t>(VT_HANDLE, 0);
  }
  FB::CmdOutput_t t_type() const {
    return static_cast<FB::CmdOutput_t>(GetField<uint8_t>(VT_T_TYPE, 0));
  }
  const void *t() const {
    return GetPointer<const void *>(VT_T);
  }
  template<typename T> const T *t_as() const;
  const FB::CmdOutputNone *t_as_CmdOutputNone() const {
    return t_type() == FB::CmdOutput_t_CmdOutputNone ? static_cast<const FB::CmdOutputNone *>(t()) : nullptr;
  }
  const FB::CmdOutputGetRegmem *t_as_CmdOutputGetRegmem() const {
    return t_type() == FB::CmdOutput_t_CmdOutputGetRegmem ? static_cast<const FB::CmdOutputGetRegmem *>(t()) : nullptr;
  }
  const FB::CmdOutputGetNeuron *t_as_CmdOutputGetNeuron() const {
    return t_type() == FB::CmdOutput_t_CmdOutputGetNeuron ? static_cast<const FB::CmdOutputGetNeuron *>(t()) : nullptr;
  }
  const FB::CmdOutputGetSynapse *t_as_CmdOutputGetSynapse() const {
    return t_type() == FB::CmdOutput_t_CmdOutputGetSynapse ? static_cast<const FB::CmdOutputGetSynapse *>(t()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_HANDLE, 4) &&
           VerifyField<uint8_t>(verifier, VT_T_TYPE, 1) &&
           VerifyOffset(verifier, VT_T) &&
           VerifyCmdOutput_t(verifier, t(), t_type()) &&
           verifier.EndTable();
  }
  CmdOutputT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CmdOutputT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CmdOutput> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const FB::CmdOutputNone *CmdOutput::t_as<FB::CmdOutputNone>() const {
  return t_as_CmdOutputNone();
}

template<> inline const FB::CmdOutputGetRegmem *CmdOutput::t_as<FB::CmdOutputGetRegmem>() const {
  return t_as_CmdOutputGetRegmem();
}

template<> inline const FB::CmdOutputGetNeuron *CmdOutput::t_as<FB::CmdOutputGetNeuron>() const {
  return t_as_CmdOutputGetNeuron();
}

template<> inline const FB::CmdOutputGetSynapse *CmdOutput::t_as<FB::CmdOutputGetSynapse>() const {
  return t_as_CmdOutputGetSynapse();
}

struct CmdOutputBuilder {
  typedef CmdOutput Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_handle(uint32_t handle) {
    fbb_.AddElement<uint32_t>(CmdOutput::VT_HANDLE, handle, 0);
  }
  void add_t_type(FB::CmdOutput_t t_type) {
    fbb_.AddElement<uint8_t>(CmdOutput::VT_T_TYPE, static_cast<uint8_t>(t_type), 0);
  }
  void add_t(::flatbuffers::Offset<void> t) {
    fbb_.AddOffset(CmdOutput::VT_T, t);
  }
  explicit CmdOutputBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdOutput> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdOutput>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdOutput> CreateCmdOutput(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t handle = 0,
    FB::CmdOutput_t t_type = FB::CmdOutput_t_NONE,
    ::flatbuffers::Offset<void> t = 0) {
  CmdOutputBuilder builder_(_fbb);
  builder_.add_t(t);
  builder_.add_handle(handle);
  builder_.add_t_type(t_type);
  return builder_.Finish();
}

::flatbuffers::Offset<CmdOutput> CreateCmdOutput(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CmdOutputNoneT *CmdOutputNone::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdOutputNoneT>(new CmdOutputNoneT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdOutputNone::UnPackTo(CmdOutputNoneT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<CmdOutputNone> CreateCmdOutputNone(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputNoneT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdOutputNone::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdOutputNone> CmdOutputNone::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputNoneT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdOutputNoneT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return FB::CreateCmdOutputNone(
      _fbb);
}

inline CmdOutputGetRegmemT::CmdOutputGetRegmemT(const CmdOutputGetRegmemT &o)
      : core_id(o.core_id),
        regmem((o.regmem) ? new FB::OdinRegmem(*o.regmem) : nullptr) {
}

inline CmdOutputGetRegmemT &CmdOutputGetRegmemT::operator=(CmdOutputGetRegmemT o) FLATBUFFERS_NOEXCEPT {
  std::swap(core_id, o.core_id);
  std::swap(regmem, o.regmem);
  return *this;
}

inline CmdOutputGetRegmemT *CmdOutputGetRegmem::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdOutputGetRegmemT>(new CmdOutputGetRegmemT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdOutputGetRegmem::UnPackTo(CmdOutputGetRegmemT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = regmem(); if (_e) _o->regmem = std::unique_ptr<FB::OdinRegmem>(new FB::OdinRegmem(*_e)); }
}

inline ::flatbuffers::Offset<CmdOutputGetRegmem> CreateCmdOutputGetRegmem(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetRegmemT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdOutputGetRegmem::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdOutputGetRegmem> CmdOutputGetRegmem::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetRegmemT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdOutputGetRegmemT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _regmem = _o->regmem ? _o->regmem.get() : nullptr;
  return FB::CreateCmdOutputGetRegmem(
      _fbb,
      _core_id,
      _regmem);
}

inline CmdOutputGetNeuronT::CmdOutputGetNeuronT(const CmdOutputGetNeuronT &o)
      : core_id(o.core_id),
        neur_id(o.neur_id),
        neuron_words((o.neuron_words) ? new FB::NeuronWords128(*o.neuron_words) : nullptr) {
}

inline CmdOutputGetNeuronT &CmdOutputGetNeuronT::operator=(CmdOutputGetNeuronT o) FLATBUFFERS_NOEXCEPT {
  std::swap(core_id, o.core_id);
  std::swap(neur_id, o.neur_id);
  std::swap(neuron_words, o.neuron_words);
  return *this;
}

inline CmdOutputGetNeuronT *CmdOutputGetNeuron::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdOutputGetNeuronT>(new CmdOutputGetNeuronT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdOutputGetNeuron::UnPackTo(CmdOutputGetNeuronT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = neur_id(); _o->neur_id = _e; }
  { auto _e = neuron_words(); if (_e) _o->neuron_words = std::unique_ptr<FB::NeuronWords128>(new FB::NeuronWords128(*_e)); }
}

inline ::flatbuffers::Offset<CmdOutputGetNeuron> CreateCmdOutputGetNeuron(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetNeuronT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdOutputGetNeuron::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdOutputGetNeuron> CmdOutputGetNeuron::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetNeuronT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdOutputGetNeuronT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _neur_id = _o->neur_id;
  auto _neuron_words = _o->neuron_words ? _o->neuron_words.get() : nullptr;
  return FB::CreateCmdOutputGetNeuron(
      _fbb,
      _core_id,
      _neur_id,
      _neuron_words);
}

inline CmdOutputGetSynapseT *CmdOutputGetSynapse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdOutputGetSynapseT>(new CmdOutputGetSynapseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdOutputGetSynapse::UnPackTo(CmdOutputGetSynapseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = pre_neur_id(); _o->pre_neur_id = _e; }
  { auto _e = post_neur_id(); _o->post_neur_id = _e; }
  { auto _e = weight(); _o->weight = _e; }
}

inline ::flatbuffers::Offset<CmdOutputGetSynapse> CreateCmdOutputGetSynapse(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetSynapseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdOutputGetSynapse::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdOutputGetSynapse> CmdOutputGetSynapse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputGetSynapseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdOutputGetSynapseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _pre_neur_id = _o->pre_neur_id;
  auto _post_neur_id = _o->post_neur_id;
  auto _weight = _o->weight;
  return FB::CreateCmdOutputGetSynapse(
      _fbb,
      _core_id,
      _pre_neur_id,
      _post_neur_id,
      _weight);
}

inline CmdOutputT *CmdOutput::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CmdOutputT>(new CmdOutputT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CmdOutput::UnPackTo(CmdOutputT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = handle(); _o->handle = _e; }
  { auto _e = t_type(); _o->t.type = _e; }
  { auto _e = t(); if (_e) _o->t.value = FB::CmdOutput_tUnion::UnPack(_e, t_type(), _resolver); }
}

inline ::flatbuffers::Offset<CmdOutput> CreateCmdOutput(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CmdOutput::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CmdOutput> CmdOutput::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CmdOutputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CmdOutputT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _handle = _o->handle;
  auto _t_type = _o->t.type;
  auto _t = _o->t.Pack(_fbb);
  return FB::CreateCmdOutput(
      _fbb,
      _handle,
      _t_type,
      _t);
}

template <bool B>
inline bool VerifyCmdOutput_t(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, CmdOutput_t type) {
  switch (type) {
    case CmdOutput_t_NONE: {
      return true;
    }
    case CmdOutput_t_CmdOutputNone: {
      auto ptr = reinterpret_cast<const FB::CmdOutputNone *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CmdOutput_t_CmdOutputGetRegmem: {
      auto ptr = reinterpret_cast<const FB::CmdOutputGetRegmem *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CmdOutput_t_CmdOutputGetNeuron: {
      auto ptr = reinterpret_cast<const FB::CmdOutputGetNeuron *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CmdOutput_t_CmdOutputGetSynapse: {
      auto ptr = reinterpret_cast<const FB::CmdOutputGetSynapse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyCmdOutput_tVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCmdOutput_t(
        verifier,  values->Get(i), types->GetEnum<CmdOutput_t>(i))) {
      return false;
    }
  }
  return true;
}

inline void *CmdOutput_tUnion::UnPack(const void *obj, CmdOutput_t type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case CmdOutput_t_CmdOutputNone: {
      auto ptr = reinterpret_cast<const FB::CmdOutputNone *>(obj);
      return ptr->UnPack(resolver);
    }
    case CmdOutput_t_CmdOutputGetRegmem: {
      auto ptr = reinterpret_cast<const FB::CmdOutputGetRegmem *>(obj);
      return ptr->UnPack(resolver);
    }
    case CmdOutput_t_CmdOutputGetNeuron: {
      auto ptr = reinterpret_cast<const FB::CmdOutputGetNeuron *>(obj);
      return ptr->UnPack(resolver);
    }
    case CmdOutput_t_CmdOutputGetSynapse: {
      auto ptr = reinterpret_cast<const FB::CmdOutputGetSynapse *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> CmdOutput_tUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case CmdOutput_t_CmdOutputNone: {
      auto ptr = reinterpret_cast<const FB::CmdOutputNoneT *>(value);
      return CreateCmdOutputNone(_fbb, ptr, _rehasher).Union();
    }
    case CmdOutput_t_CmdOutputGetRegmem: {
      auto ptr = reinterpret_cast<const FB::CmdOutputGetRegmemT *>(value);
      return CreateCmdOutputGetRegmem(_fbb, ptr, _rehasher).Union();
    }
    case CmdOutput_t_CmdOutputGetNeuron: {
      auto ptr = reinterpret_cast<const FB::CmdOutputGetNeuronT *>(value);
      return CreateCmdOutputGetNeuron(_fbb, ptr, _rehasher).Union();
    }
    case CmdOutput_t_CmdOutputGetSynapse: {
      auto ptr = reinterpret_cast<const FB::CmdOutputGetSynapseT *>(value);
      return CreateCmdOutputGetSynapse(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline CmdOutput_tUnion::CmdOutput_tUnion(const CmdOutput_tUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case CmdOutput_t_CmdOutputNone: {
      value = new FB::CmdOutputNoneT(*reinterpret_cast<FB::CmdOutputNoneT *>(u.value));
      break;
    }
    case CmdOutput_t_CmdOutputGetRegmem: {
      value = new FB::CmdOutputGetRegmemT(*reinterpret_cast<FB::CmdOutputGetRegmemT *>(u.value));
      break;
    }
    case CmdOutput_t_CmdOutputGetNeuron: {
      value = new FB::CmdOutputGetNeuronT(*reinterpret_cast<FB::CmdOutputGetNeuronT *>(u.value));
      break;
    }
    case CmdOutput_t_CmdOutputGetSynapse: {
      value = new FB::CmdOutputGetSynapseT(*reinterpret_cast<FB::CmdOutputGetSynapseT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void CmdOutput_tUnion::Reset() {
  switch (type) {
    case CmdOutput_t_CmdOutputNone: {
      auto ptr = reinterpret_cast<FB::CmdOutputNoneT *>(value);
      delete ptr;
      break;
    }
    case CmdOutput_t_CmdOutputGetRegmem: {
      auto ptr = reinterpret_cast<FB::CmdOutputGetRegmemT *>(value);
      delete ptr;
      break;
    }
    case CmdOutput_t_CmdOutputGetNeuron: {
      auto ptr = reinterpret_cast<FB::CmdOutputGetNeuronT *>(value);
      delete ptr;
      break;
    }
    case CmdOutput_t_CmdOutputGetSynapse: {
      auto ptr = reinterpret_cast<FB::CmdOutputGetSynapseT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = CmdOutput_t_NONE;
}

}  // namespace FB

#endif  // FLATBUFFERS_GENERATED_CMDOUTPUT_FB_H_
