// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_INPUT_FB_H_
#define FLATBUFFERS_GENERATED_INPUT_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "cmd_generated.h"

namespace FB {

struct Input;
struct InputBuilder;
struct InputT;

struct InputT : public ::flatbuffers::NativeTable {
  typedef Input TableType;
  std::vector<std::unique_ptr<FB::CmdT>> commands{};
  InputT() = default;
  InputT(const InputT &o);
  InputT(InputT&&) FLATBUFFERS_NOEXCEPT = default;
  InputT &operator=(InputT o) FLATBUFFERS_NOEXCEPT;
};

struct Input FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InputT NativeTableType;
  typedef InputBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COMMANDS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<FB::Cmd>> *commands() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FB::Cmd>> *>(VT_COMMANDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COMMANDS) &&
           verifier.VerifyVector(commands()) &&
           verifier.VerifyVectorOfTables(commands()) &&
           verifier.EndTable();
  }
  InputT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(InputT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Input> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct InputBuilder {
  typedef Input Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_commands(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB::Cmd>>> commands) {
    fbb_.AddOffset(Input::VT_COMMANDS, commands);
  }
  explicit InputBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Input> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Input>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Input> CreateInput(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB::Cmd>>> commands = 0) {
  InputBuilder builder_(_fbb);
  builder_.add_commands(commands);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Input> CreateInputDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<FB::Cmd>> *commands = nullptr) {
  auto commands__ = commands ? _fbb.CreateVector<::flatbuffers::Offset<FB::Cmd>>(*commands) : 0;
  return FB::CreateInput(
      _fbb,
      commands__);
}

::flatbuffers::Offset<Input> CreateInput(::flatbuffers::FlatBufferBuilder &_fbb, const InputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline InputT::InputT(const InputT &o) {
  commands.reserve(o.commands.size());
  for (const auto &commands_ : o.commands) { commands.emplace_back((commands_) ? new FB::CmdT(*commands_) : nullptr); }
}

inline InputT &InputT::operator=(InputT o) FLATBUFFERS_NOEXCEPT {
  std::swap(commands, o.commands);
  return *this;
}

inline InputT *Input::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<InputT>(new InputT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Input::UnPackTo(InputT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = commands(); if (_e) { _o->commands.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->commands[_i]) { _e->Get(_i)->UnPackTo(_o->commands[_i].get(), _resolver); } else { _o->commands[_i] = std::unique_ptr<FB::CmdT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->commands.resize(0); } }
}

inline ::flatbuffers::Offset<Input> CreateInput(::flatbuffers::FlatBufferBuilder &_fbb, const InputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Input::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Input> Input::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const InputT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _commands = _o->commands.size() ? _fbb.CreateVector<::flatbuffers::Offset<FB::Cmd>> (_o->commands.size(), [](size_t i, _VectorArgs *__va) { return CreateCmd(*__va->__fbb, __va->__o->commands[i].get(), __va->__rehasher); }, &_va ) : 0;
  return FB::CreateInput(
      _fbb,
      _commands);
}

inline const FB::Input *GetInput(const void *buf) {
  return ::flatbuffers::GetRoot<FB::Input>(buf);
}

inline const FB::Input *GetSizePrefixedInput(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB::Input>(buf);
}

template <bool B = false>
inline bool VerifyInputBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB::Input>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedInputBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB::Input>(nullptr);
}

inline void FinishInputBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB::Input> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedInputBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB::Input> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<FB::InputT> UnPackInput(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<FB::InputT>(GetInput(buf)->UnPack(res));
}

inline std::unique_ptr<FB::InputT> UnPackSizePrefixedInput(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<FB::InputT>(GetSizePrefixedInput(buf)->UnPack(res));
}

}  // namespace FB

#endif  // FLATBUFFERS_GENERATED_INPUT_FB_H_
