// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ODINTYPES_FB_H_
#define FLATBUFFERS_GENERATED_ODINTYPES_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace FB {

struct OdinRegmem;

struct NeuronWords128;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) OdinRegmem FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t open_loop_;
  uint32_t syn_sign_[8];
  uint32_t reserved_syn_sign_[8];
  uint32_t burst_timeref_;
  uint32_t aer_src_ctrl_nneur_;
  uint32_t out_aer_monitor_en_;
  uint32_t monitor_neur_addr_;
  uint32_t monitor_syn_addr_;
  uint32_t update_unmapped_syn_;
  uint32_t propagate_unmapped_syn_;
  uint32_t sdsp_on_syn_stim_;

 public:
  OdinRegmem()
      : open_loop_(0),
        syn_sign_(),
        reserved_syn_sign_(),
        burst_timeref_(0),
        aer_src_ctrl_nneur_(0),
        out_aer_monitor_en_(0),
        monitor_neur_addr_(0),
        monitor_syn_addr_(0),
        update_unmapped_syn_(0),
        propagate_unmapped_syn_(0),
        sdsp_on_syn_stim_(0) {
  }
  OdinRegmem(uint32_t _open_loop, uint32_t _burst_timeref, uint32_t _aer_src_ctrl_nneur, uint32_t _out_aer_monitor_en, uint32_t _monitor_neur_addr, uint32_t _monitor_syn_addr, uint32_t _update_unmapped_syn, uint32_t _propagate_unmapped_syn, uint32_t _sdsp_on_syn_stim)
      : open_loop_(::flatbuffers::EndianScalar(_open_loop)),
        syn_sign_(),
        reserved_syn_sign_(),
        burst_timeref_(::flatbuffers::EndianScalar(_burst_timeref)),
        aer_src_ctrl_nneur_(::flatbuffers::EndianScalar(_aer_src_ctrl_nneur)),
        out_aer_monitor_en_(::flatbuffers::EndianScalar(_out_aer_monitor_en)),
        monitor_neur_addr_(::flatbuffers::EndianScalar(_monitor_neur_addr)),
        monitor_syn_addr_(::flatbuffers::EndianScalar(_monitor_syn_addr)),
        update_unmapped_syn_(::flatbuffers::EndianScalar(_update_unmapped_syn)),
        propagate_unmapped_syn_(::flatbuffers::EndianScalar(_propagate_unmapped_syn)),
        sdsp_on_syn_stim_(::flatbuffers::EndianScalar(_sdsp_on_syn_stim)) {
  }
  OdinRegmem(uint32_t _open_loop, ::flatbuffers::span<const uint32_t, 8> _syn_sign, ::flatbuffers::span<const uint32_t, 8> _reserved_syn_sign, uint32_t _burst_timeref, uint32_t _aer_src_ctrl_nneur, uint32_t _out_aer_monitor_en, uint32_t _monitor_neur_addr, uint32_t _monitor_syn_addr, uint32_t _update_unmapped_syn, uint32_t _propagate_unmapped_syn, uint32_t _sdsp_on_syn_stim)
      : open_loop_(::flatbuffers::EndianScalar(_open_loop)),
        burst_timeref_(::flatbuffers::EndianScalar(_burst_timeref)),
        aer_src_ctrl_nneur_(::flatbuffers::EndianScalar(_aer_src_ctrl_nneur)),
        out_aer_monitor_en_(::flatbuffers::EndianScalar(_out_aer_monitor_en)),
        monitor_neur_addr_(::flatbuffers::EndianScalar(_monitor_neur_addr)),
        monitor_syn_addr_(::flatbuffers::EndianScalar(_monitor_syn_addr)),
        update_unmapped_syn_(::flatbuffers::EndianScalar(_update_unmapped_syn)),
        propagate_unmapped_syn_(::flatbuffers::EndianScalar(_propagate_unmapped_syn)),
        sdsp_on_syn_stim_(::flatbuffers::EndianScalar(_sdsp_on_syn_stim)) {
    ::flatbuffers::CastToArray(syn_sign_).CopyFromSpan(_syn_sign);
    ::flatbuffers::CastToArray(reserved_syn_sign_).CopyFromSpan(_reserved_syn_sign);
  }
  uint32_t open_loop() const {
    return ::flatbuffers::EndianScalar(open_loop_);
  }
  const ::flatbuffers::Array<uint32_t, 8> *syn_sign() const {
    return &::flatbuffers::CastToArray(syn_sign_);
  }
  const ::flatbuffers::Array<uint32_t, 8> *reserved_syn_sign() const {
    return &::flatbuffers::CastToArray(reserved_syn_sign_);
  }
  uint32_t burst_timeref() const {
    return ::flatbuffers::EndianScalar(burst_timeref_);
  }
  uint32_t aer_src_ctrl_nneur() const {
    return ::flatbuffers::EndianScalar(aer_src_ctrl_nneur_);
  }
  uint32_t out_aer_monitor_en() const {
    return ::flatbuffers::EndianScalar(out_aer_monitor_en_);
  }
  uint32_t monitor_neur_addr() const {
    return ::flatbuffers::EndianScalar(monitor_neur_addr_);
  }
  uint32_t monitor_syn_addr() const {
    return ::flatbuffers::EndianScalar(monitor_syn_addr_);
  }
  uint32_t update_unmapped_syn() const {
    return ::flatbuffers::EndianScalar(update_unmapped_syn_);
  }
  uint32_t propagate_unmapped_syn() const {
    return ::flatbuffers::EndianScalar(propagate_unmapped_syn_);
  }
  uint32_t sdsp_on_syn_stim() const {
    return ::flatbuffers::EndianScalar(sdsp_on_syn_stim_);
  }
};
FLATBUFFERS_STRUCT_END(OdinRegmem, 100);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) NeuronWords128 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t words_[4];

 public:
  NeuronWords128()
      : words_() {
  }
  NeuronWords128(::flatbuffers::span<const uint32_t, 4> _words) {
    ::flatbuffers::CastToArray(words_).CopyFromSpan(_words);
  }
  const ::flatbuffers::Array<uint32_t, 4> *words() const {
    return &::flatbuffers::CastToArray(words_);
  }
};
FLATBUFFERS_STRUCT_END(NeuronWords128, 16);

}  // namespace FB

#endif  // FLATBUFFERS_GENERATED_ODINTYPES_FB_H_
