// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OUTPUT_FB_H_
#define FLATBUFFERS_GENERATED_OUTPUT_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "cmd_generated.h"
#include "cmd_output_generated.h"

namespace FB {

struct Message;
struct MessageBuilder;
struct MessageT;

struct Spikes;
struct SpikesBuilder;
struct SpikesT;

struct Output;
struct OutputBuilder;
struct OutputT;

enum MessageType : uint8_t {
  MessageType_INFO = 0,
  MessageType_WARNING = 1,
  MessageType_ERROR = 2,
  MessageType_DEBUG = 3,
  MessageType_MIN = MessageType_INFO,
  MessageType_MAX = MessageType_DEBUG
};

inline const MessageType (&EnumValuesMessageType())[4] {
  static const MessageType values[] = {
    MessageType_INFO,
    MessageType_WARNING,
    MessageType_ERROR,
    MessageType_DEBUG
  };
  return values;
}

inline const char * const *EnumNamesMessageType() {
  static const char * const names[5] = {
    "INFO",
    "WARNING",
    "ERROR",
    "DEBUG",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageType(MessageType e) {
  if (::flatbuffers::IsOutRange(e, MessageType_INFO, MessageType_DEBUG)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageType()[index];
}

struct MessageT : public ::flatbuffers::NativeTable {
  typedef Message TableType;
  FB::MessageType type = FB::MessageType_INFO;
  std::string text{};
};

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageT NativeTableType;
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_TEXT = 6
  };
  FB::MessageType type() const {
    return static_cast<FB::MessageType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::String *text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_TEXT) &&
           verifier.VerifyString(text()) &&
           verifier.EndTable();
  }
  MessageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MessageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Message> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(FB::MessageType type) {
    fbb_.AddElement<uint8_t>(Message::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_text(::flatbuffers::Offset<::flatbuffers::String> text) {
    fbb_.AddOffset(Message::VT_TEXT, text);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FB::MessageType type = FB::MessageType_INFO,
    ::flatbuffers::Offset<::flatbuffers::String> text = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_text(text);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Message> CreateMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FB::MessageType type = FB::MessageType_INFO,
    const char *text = nullptr) {
  auto text__ = text ? _fbb.CreateString(text) : 0;
  return FB::CreateMessage(
      _fbb,
      type,
      text__);
}

::flatbuffers::Offset<Message> CreateMessage(::flatbuffers::FlatBufferBuilder &_fbb, const MessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SpikesT : public ::flatbuffers::NativeTable {
  typedef Spikes TableType;
  uint8_t core_id = 0;
  std::vector<uint8_t> words{};
};

struct Spikes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SpikesT NativeTableType;
  typedef SpikesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CORE_ID = 4,
    VT_WORDS = 6
  };
  uint8_t core_id() const {
    return GetField<uint8_t>(VT_CORE_ID, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *words() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_WORDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CORE_ID, 1) &&
           VerifyOffset(verifier, VT_WORDS) &&
           verifier.VerifyVector(words()) &&
           verifier.EndTable();
  }
  SpikesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SpikesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Spikes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SpikesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SpikesBuilder {
  typedef Spikes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_core_id(uint8_t core_id) {
    fbb_.AddElement<uint8_t>(Spikes::VT_CORE_ID, core_id, 0);
  }
  void add_words(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> words) {
    fbb_.AddOffset(Spikes::VT_WORDS, words);
  }
  explicit SpikesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Spikes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Spikes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Spikes> CreateSpikes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> words = 0) {
  SpikesBuilder builder_(_fbb);
  builder_.add_words(words);
  builder_.add_core_id(core_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Spikes> CreateSpikesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t core_id = 0,
    const std::vector<uint8_t> *words = nullptr) {
  auto words__ = words ? _fbb.CreateVector<uint8_t>(*words) : 0;
  return FB::CreateSpikes(
      _fbb,
      core_id,
      words__);
}

::flatbuffers::Offset<Spikes> CreateSpikes(::flatbuffers::FlatBufferBuilder &_fbb, const SpikesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct OutputT : public ::flatbuffers::NativeTable {
  typedef Output TableType;
  std::unique_ptr<FB::MessageT> message{};
  std::unique_ptr<FB::SpikesT> spikes{};
  std::unique_ptr<FB::CmdOutputT> cmd_output{};
  OutputT() = default;
  OutputT(const OutputT &o);
  OutputT(OutputT&&) FLATBUFFERS_NOEXCEPT = default;
  OutputT &operator=(OutputT o) FLATBUFFERS_NOEXCEPT;
};

struct Output FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OutputT NativeTableType;
  typedef OutputBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE = 4,
    VT_SPIKES = 6,
    VT_CMD_OUTPUT = 8
  };
  const FB::Message *message() const {
    return GetPointer<const FB::Message *>(VT_MESSAGE);
  }
  const FB::Spikes *spikes() const {
    return GetPointer<const FB::Spikes *>(VT_SPIKES);
  }
  const FB::CmdOutput *cmd_output() const {
    return GetPointer<const FB::CmdOutput *>(VT_CMD_OUTPUT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyTable(message()) &&
           VerifyOffset(verifier, VT_SPIKES) &&
           verifier.VerifyTable(spikes()) &&
           VerifyOffset(verifier, VT_CMD_OUTPUT) &&
           verifier.VerifyTable(cmd_output()) &&
           verifier.EndTable();
  }
  OutputT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(OutputT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Output> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const OutputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct OutputBuilder {
  typedef Output Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message(::flatbuffers::Offset<FB::Message> message) {
    fbb_.AddOffset(Output::VT_MESSAGE, message);
  }
  void add_spikes(::flatbuffers::Offset<FB::Spikes> spikes) {
    fbb_.AddOffset(Output::VT_SPIKES, spikes);
  }
  void add_cmd_output(::flatbuffers::Offset<FB::CmdOutput> cmd_output) {
    fbb_.AddOffset(Output::VT_CMD_OUTPUT, cmd_output);
  }
  explicit OutputBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Output> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Output>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Output> CreateOutput(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FB::Message> message = 0,
    ::flatbuffers::Offset<FB::Spikes> spikes = 0,
    ::flatbuffers::Offset<FB::CmdOutput> cmd_output = 0) {
  OutputBuilder builder_(_fbb);
  builder_.add_cmd_output(cmd_output);
  builder_.add_spikes(spikes);
  builder_.add_message(message);
  return builder_.Finish();
}

::flatbuffers::Offset<Output> CreateOutput(::flatbuffers::FlatBufferBuilder &_fbb, const OutputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline MessageT *Message::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MessageT>(new MessageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Message::UnPackTo(MessageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = text(); if (_e) _o->text = _e->str(); }
}

inline ::flatbuffers::Offset<Message> CreateMessage(::flatbuffers::FlatBufferBuilder &_fbb, const MessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Message::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Message> Message::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MessageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _text = _o->text.empty() ? 0 : _fbb.CreateString(_o->text);
  return FB::CreateMessage(
      _fbb,
      _type,
      _text);
}

inline SpikesT *Spikes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SpikesT>(new SpikesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Spikes::UnPackTo(SpikesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = core_id(); _o->core_id = _e; }
  { auto _e = words(); if (_e) { _o->words.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->words.begin()); } }
}

inline ::flatbuffers::Offset<Spikes> CreateSpikes(::flatbuffers::FlatBufferBuilder &_fbb, const SpikesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Spikes::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Spikes> Spikes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SpikesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SpikesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _core_id = _o->core_id;
  auto _words = _o->words.size() ? _fbb.CreateVector(_o->words) : 0;
  return FB::CreateSpikes(
      _fbb,
      _core_id,
      _words);
}

inline OutputT::OutputT(const OutputT &o)
      : message((o.message) ? new FB::MessageT(*o.message) : nullptr),
        spikes((o.spikes) ? new FB::SpikesT(*o.spikes) : nullptr),
        cmd_output((o.cmd_output) ? new FB::CmdOutputT(*o.cmd_output) : nullptr) {
}

inline OutputT &OutputT::operator=(OutputT o) FLATBUFFERS_NOEXCEPT {
  std::swap(message, o.message);
  std::swap(spikes, o.spikes);
  std::swap(cmd_output, o.cmd_output);
  return *this;
}

inline OutputT *Output::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<OutputT>(new OutputT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Output::UnPackTo(OutputT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = message(); if (_e) { if(_o->message) { _e->UnPackTo(_o->message.get(), _resolver); } else { _o->message = std::unique_ptr<FB::MessageT>(_e->UnPack(_resolver)); } } else if (_o->message) { _o->message.reset(); } }
  { auto _e = spikes(); if (_e) { if(_o->spikes) { _e->UnPackTo(_o->spikes.get(), _resolver); } else { _o->spikes = std::unique_ptr<FB::SpikesT>(_e->UnPack(_resolver)); } } else if (_o->spikes) { _o->spikes.reset(); } }
  { auto _e = cmd_output(); if (_e) { if(_o->cmd_output) { _e->UnPackTo(_o->cmd_output.get(), _resolver); } else { _o->cmd_output = std::unique_ptr<FB::CmdOutputT>(_e->UnPack(_resolver)); } } else if (_o->cmd_output) { _o->cmd_output.reset(); } }
}

inline ::flatbuffers::Offset<Output> CreateOutput(::flatbuffers::FlatBufferBuilder &_fbb, const OutputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Output::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Output> Output::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const OutputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const OutputT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _message = _o->message ? CreateMessage(_fbb, _o->message.get(), _rehasher) : 0;
  auto _spikes = _o->spikes ? CreateSpikes(_fbb, _o->spikes.get(), _rehasher) : 0;
  auto _cmd_output = _o->cmd_output ? CreateCmdOutput(_fbb, _o->cmd_output.get(), _rehasher) : 0;
  return FB::CreateOutput(
      _fbb,
      _message,
      _spikes,
      _cmd_output);
}

inline const FB::Output *GetOutput(const void *buf) {
  return ::flatbuffers::GetRoot<FB::Output>(buf);
}

inline const FB::Output *GetSizePrefixedOutput(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB::Output>(buf);
}

template <bool B = false>
inline bool VerifyOutputBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB::Output>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedOutputBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB::Output>(nullptr);
}

inline void FinishOutputBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB::Output> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOutputBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB::Output> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<FB::OutputT> UnPackOutput(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<FB::OutputT>(GetOutput(buf)->UnPack(res));
}

inline std::unique_ptr<FB::OutputT> UnPackSizePrefixedOutput(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<FB::OutputT>(GetSizePrefixedOutput(buf)->UnPack(res));
}

}  // namespace FB

#endif  // FLATBUFFERS_GENERATED_OUTPUT_FB_H_
